const Alexa = require('alexa-sdk')
const APP_ID = ''

const languageStrings = {
  'de-DE': {
    'translation': {
      'SKILL_NAME': 'Liebe ist',
      'HELP_MESSAGE': "Ich lese Dir einen Liebe ist Spruch vor.",
      'STOP_MESSAGE': 'Tschüss'
    }
  }
}


const loveIs = [
  "Liebe ist ... jemandem wiederzusehen, nach vielen Jahren.",
  "Liebe ist ... Super)).",
  "Liebe ist ... den andren auch mal auf der Couch schlafen zulassen.",
  "Liebe ist ... Wein.",
  "Liebe ist ... wenn er ihr die Scheibe freikratzt.",
  "Liebe ist ... Liebe ist wenn man nicht geht, sondern schwebt.",
  "Liebe ist ... Wie ein Hooligan.",
  "Liebe ist ... Gemeinsamkeiten zu haben.",
  "Liebe ist ... gleich nach dem Aufwachen an sie zu denken.",
  "Liebe ist ... unglaublich toll.",
  "Liebe ist ... wenn Er alles tut, damit es Ihr gut geht.",
  "Liebe ist ... Liebe ist.",
  "Liebe ist ... einfach wunderbar.",
  "Liebe ist ... unbezahlbar wundervoll.",
  "Liebe ist ... dieselben Sneaker zu tragen.",
  "Liebe ist ... wenn man sich aufs Wiedersehen immer wieder freut.",
  "Liebe ist ... wenn zwei Herzen im gleichen Takt schlagen.",
  "Liebe ist ... sich mit ihm abends einen Joghurt zu teilen.",
  "Liebe ist ... ihr die Zukunft zu sichern.",
  "Liebe ist ... wenn zwei Menschen die goldene Hochzeit feiern und sich lieb wie am ersten Tag.",
  "Liebe ist ... wenn es ohne ihn nur noch halb so schön ist.",
  "Liebe ist ... wie der Geschmack von Wasser.",
  "Liebe ist ... Das kann man nicht erklären.",
  "Liebe ist ... ihm Sonnenstrahlen von KA nach TÜ zu schicken, auch bei Regen.",
  "Liebe ist ... zusammen alt zu werden.",
  "Liebe ist ... wenn man sich sicher ist, dass man den Rest seines Lebens mit ihm oder ihr verbringen möchte.",
  "Liebe ist ... wenn alle Songs plötzlich Sinn ergeben.",
  "Liebe ist ... Freunde auf Eis zu legen, wenn sie im Krankenhaus liegt.",
  "Liebe ist ... für manche so viel, doch für mich bist es nur Du.",
  "Liebe ist ... wenn man Schmetterlinge im Bauch hat.",
  "Liebe ist ... unendlich schön.",
  "Liebe ist ... ist eine Himmelsmacht.",
  "Liebe ist ... unsterblich.",
  "Liebe ist ... wenn aus zwei Herzen drei werden.",
  "Liebe ist ... wenn aus einem Du und Ich ein WIR wird.",
  "Liebe ist ... keine Äußerlichkeit.",
  "Liebe ist ... auf die Meinung der Anderen zu scheißen.",
  "Liebe ist ... ihm auch mal zu verzeihen.",
  "Liebe ist ... einfach unverbesserlich.",
  "Liebe ist ... wenn er auch mal morgens mit dem Hund geht.",
  "Liebe ist ... so wie du bist.",
  "Liebe ist ... ihr das Shampoo auf die Heizung zu stellen.",
  "Liebe ist ... schon 12 Jahre lang.",
  "Liebe ist ... all das, was ich mit dir erlebe.",
  "Liebe ist ... sein Herz zu verschenken, weil man weiß, dass es gut behütet wird.",
  "Liebe ist ... seinen Partner einfach mal im Office anzurufen und zu sagen, dass man ihn grad vermisst.",
  "Liebe ist ... wenn er immer zu dir runter schaut und lächelt.",
  "Liebe ist ... Forever.",
  "Liebe ist ... Ja zu sagen.",
  "Liebe ist ... die Gegensätze zu ergänzen.",
  "Liebe ist ... wenn Dein Mann Dir morgens Dein Auto vom Schnee befreit.",
  "Liebe ist ... mit ihr in den BvB Tempel zu gehen.",
  "Liebe ist ... zu sehen, wer im Leben die richtige Liebe war und ist! Für immer Deins Esmeray, für immer eins.",
  "Liebe ist ... wenn sie Lilli heisst und mit dir verheiratet ist.",
  "Liebe ist ... einander nah zu sein, auch wenn der andere nicht da ist.",
  "Liebe ist ... seine/ihre Gedankensprünge nachzuvollziehen.",
  "Liebe ist ... wenn man nachts vor dem Einschlafen an sie/ihn denkt.",
  "Liebe ist ... auch nach 34 Jahren noch schön.",
  "Liebe ist ... gemeinsam Star Wars zu zitieren.",
  "Liebe ist ... einen gemeinsamen Moment zu haben, den keiner der beiden je wieder vergessen kann.",
  "Liebe ist ... gemeinsam in ein neues Jahr zu gehen.",
  "Liebe ist ... zu lachen, auch wenn man müde ist.",
  "Liebe ist ... Alles, und zudem die stärkste Kraft im Universum.",
  "Liebe ist ... nach 18 Jahren herauszufinden, dass man zusammen gehört.",
  "Liebe ist ... stärker.",
  "Liebe ist ... den Partner jeden Tag aufs neue zu verzaubern.",
  "Liebe ist ... wie Luft, man sieht sie nicht, aber man spürt sie.",
  "Liebe ist ... wenn sie morgens bei dir aufwacht und Kaffee trinkt.",
  "Liebe ist ... mit ihr am Sonntagabend den Tatort zu gucken.",
  "Liebe ist ... immer füreinander da zu sein.",
  "Liebe ist ... die To-Do´s miteinander zu koordinieren.",
  "Liebe ist ... manchmal auch stumm.",
  "Liebe ist ... beim Schwimmen die Bahn zu teilen.",
  "Liebe ist ... ihr nicht mehr böse zu sein.",
  "Liebe ist ... wenn die Realität schöner ist als jeder Traum.",
  "Liebe ist ... Wenn Er auf der Arbeit an Sie denkt.",
  "Liebe ist ... Freundschaft.",
  "Liebe ist ... Verständnisvoll zu sein, wenn die Partnerin morgens um halb 4 Haare föhnen muss.",
  "Liebe ist ... wenn du die Welt positiv wahrnimmst.",
  "Liebe ist ... dem anderen was gutes zu essen zu machen.",
  "Liebe ist ... eine Botschaft, die man nie vergisst.",
  "Liebe ist ... wenn sich jeder Tag wie frisch verliebt anfühlt.",
  "Liebe ist ... wenn wir zwei eins sind.",
  "Liebe ist ... Wenn ein guter Freund dir jede Freiheit lässt und dich bei allem bedingugslos unterstützt, selbst wenn es ihm dabei nicht so toll geht.",
  "Liebe ist ... ein Bad zu zweit.",
  "Liebe ist ... Die Fehler seiner Maus zu akzeptieren und sie trotzdem über alles zu Lieben.",
  "Liebe ist ... Das gefühl daheim angekommen zu sein.",
  "Liebe ist ... Sich trotz großer Entfernung zu vertrauen und sich überalles zu lieben.",
  "Liebe ist ... Genial.",
  "Liebe ist ... nein, Liebe SIND wir.",
  "Liebe ist ... gemeinsam zum Eishockey zu gehen.",
  "Liebe ist ... wenn man nicht dieselbe Sprache spricht und sich trotzdem versteht.",
  "Liebe ist ... wenn er die Beziehung beendet hat und plötzlich vor der Türe steht, weil er ohne Dich nicht leben kann.",
  "Liebe ist ... einzugestehen das man einen Fehler gemacht hat und gemeinsam wieder von vorne anfängt !!!.",
  "Liebe ist ... ihn ab und zu Dampf ablassen zu lassen.",
  "Liebe ist ... wenn er vorm einschlafen nochmal ihre Stimme hören möchte.",
  "Liebe ist ... mehr Wert als Gut und Geld, es macht zwar nicht satt aber unbeschreiblich Glücklich !!!.",
  "Liebe ist ... die Geschirrspülmaschine ausräumen.",
  "Liebe ist ... wenn er den Müll rausbringt.",
  "Liebe ist ... sich zu freuen, wenn er dich sein Eigentum nennt.",
  "Liebe ist ... fühlen.",
  "Liebe ist ... dich abknutschen bis von oben bis unten.",
  "Liebe ist ... gemeinsam auf die AIDA zugehen.",
  "Liebe ist ... was Jesus Christus für uns getan hat.",
  "Liebe ist ... gemeinsam in den Tag hineinzuleben.",
  "Liebe ist ... wenn man weiß was er meint, ohne mit ihm zu sprechen.",
  "Liebe ist ... wenn das Wunschkind zum ersten mal strampelt.",
  "Liebe ist ... wenn aus eins und eins drei wird.",
  "Liebe ist ... morgens aus der Ferne ihr Handyfoto zu küssen, weil man sie vermisst.",
  "Liebe ist ... wenn man sich betrunken fühlt ohne einen einzigen Schluck Alkohol getrunken zu haben.",
  "Liebe ist ... sich darüber zu freuen, dass es dich gibt.",
  "Liebe ist ... auch den Februar gemeinsam zu überstehen.",
  "Liebe ist ... wenn ich dir in die Augen schaue und unsere Zukunft sehe, die zeigt, wie wir alt und grau in unseren Rollstühlen sitzen und uns trotzdem noch gegenseitig «Ich liebe Dich» sagen.",
  "Liebe ist ... am 12.07. Jahrestag zu haben.",
  "Liebe ist ... undefinierbar - wie Du.",
  "Liebe ist ... sich unendlich lange in die Augen schauen zu können.",
  "Liebe ist ... wenn du alles für den anderen tun willst, damit er glücklich ist.",
  "Liebe ist ... die synchrone Balance zweier Gefühle im freien Fall in die Zeit (24/7).",
  "Liebe ist ... mit Dir Roller zu fahren.",
  "Liebe ist ... ihr den Kaffee zu überlassen, obwohl sie eigentlich keinen trinkt.",
  "Liebe ist ... den Partner zu Unterstützen, wenn er arbeitslos geworden ist.",
  "Liebe ist ... wenn du angekommen bist.",
  "Liebe ist ... keinen Hunger mehr zu haben.",
  "Liebe ist ... jede Macke am Partner zu lieben.",
  "Liebe ist ... ein Blick ohne Worte.",
  "Liebe ist ... ein ewiges dran Arbeiten an einer stabilen Beziehung.",
  "Liebe ist ... Gefühle des Anderen nicht zu verletzen.",
  "Liebe ist ... nie im Streit auseinander zu gehen.",
  "Liebe ist ... sich nicht nach Meinungsverschiedenheiten, schlafen zu gehen ohne wieder zueinander gefunden haben.",
  "Liebe ist ... jemanden zu haben, mit dem man richtig schimpfen kann.",
  "Liebe ist ... so tief wie der Ozean.",
  "Liebe ist ... wenn er sie gesund pflegt.",
  "Liebe ist ... wenn ER IHR beim putzen hilft.",
  "Liebe ist ... Zusammen den Garten bearbeiten.",
  "Liebe ist ... Geborgenheit.",
  "Liebe ist ... wenn der Idiot dich zum Lachen bringt, obwohl du explodieren könntest vor Wut.",
  "Liebe ist ... niemals um Verzeihung bitten zu müssen.",
  "Liebe ist ... Schmerzhaft Schön.",
  "Liebe ist ... ein Wort ohne zu hören.",
  "Liebe ist ... grenzenlos.",
  "Liebe ist ... Man kann sie finden und verlieren.",
  "Liebe ist ... ungewiss und doch beständig.",
  "Liebe ist ... immer.",
  "Liebe ist ... jemanden zu lieben egal wie er aussieht und egal was die anderen reden, denn Liebe kommt von Herzen und das Herz hat keine Augen.",
  "Liebe ist ... ihn zu unterstützen um seine Ziele zu erreichen.",
  "Liebe ist ... wenn er sich auch mal um ihr Kind kümmert auch wenn er eigentlich nichts mit Kindern anfangen kann.",
  "Liebe ist ... wenn es einem von zweien weh tut.",
  "Liebe ist ... wenn ich jeden Tag DICH sehen darf.",
  "Liebe ist ... jeden Tag das gleiche zu Empfinden, wie von Anfang an.",
  "Liebe ist ... wenn beide ihr Handy tauschen können und nach zwei Tagen immer noch zusammen sind.",
  "Liebe ist ... wenn es für einen nur eine einzige Person auf Erden gibt.",
  "Liebe ist ... einfach ja zu sagen.",
  "Liebe ist ... auch mal nur Bilder sprechen zu lassen.",
  "Liebe ist ... immer für einander da zu sein.",
  "Liebe ist ... wie Freundschaft ... Man wird den Betreffenden nie vergessen.",
  "Liebe ist ... unbeschreibliche schön.",
  "Liebe ist ... Einen gemeinsamen Google-Kalender zu nutzen.",
  "Liebe ist ... unbeschreibliche schön.",
  "Liebe ist ... wie Drogen nehmen hart aber herzvoll.",
  "Liebe ist ... beim Kuscheln das Handy auszuschalten.",
  "Liebe ist ... ab dem ersten Augenblick zu wissen, dass man das Leben miteinander verbringen will und alles für den einen zu geben.",
  "Liebe ist ... wenn man sich ohne viele worte versteht.",
  "Liebe ist ... Und weist DU bist der richtige.",
  "Liebe ist ... ihr das Gefühl geben, sie ist die einzige auf der Welt.",
  "Liebe ist ... ihr das Gefühl geben, sie ist die einzige auf der Welt.",
  "Liebe ist ... das aller tollste Gefühl auf der ganzen Welt.",
  "Liebe ist ... wenn man an eine Person denkt ohne nachzudenken?.",
  "Liebe ist ... wo die Herzen keine Entfernung kennen, solange sie echt ist.",
  "Liebe ist ... wenn fünf Stunden zu einem wunderschönen Moment werden.",
  "Liebe ist ... einander nie mehr loslassen zu wollen.",
  "Liebe ist ... auch in schlechten Zeiten füreinander da zu sein.",
  "Liebe ist ... sich um einen zu kümmern.",
  "Liebe ist ... wenn mein Schlumpf für seine Schlumpfine Liebes Videos macht.",
  "Liebe ist ... wenn es dich mit Freude erfüllt, alles für jemanden zu tun.",
  "Liebe ist ... nur wir beide.",
  "Liebe ist ... das Schönste auf der Welt und umsonst.",
  "Liebe ist ... wenn du den Kühlschrank aufmachst, und findest einen als Geschenk verpackten Käse in Herzform.",
  "Liebe ist ... die Kraft die mein Herz zum Schlagen bringt .",
  "Liebe ist ... für immer wir zwei.",
  "Liebe ist ... sich wieder zu vertragen.",
  "Liebe ist ... ihm nicht böse zu sein.",
  "Liebe ist ... wenn die schönsten 3 Worte Ich bin glücklich sind.",
  "Liebe ist ... einfach wunderschön.",
  "Liebe ist ... das schönste Gefühl auf Erden!.",
  "Liebe ist ... wenn man ohne den anderen nicht sein kann.",
  "Liebe ist ... zusammen CSI, ,GZSZ, Welt der Tiere und Greys Anatomy zu schauen.",
  "Liebe ist ... wenn der Altersunterschied keine Rolle spielt.",
  "Liebe ist ... zu seinem Partner zu stehen.",
  "Liebe ist ... wenn er für dich auf Fußball verzichtet.",
  "Liebe ist ... gemeinsam neue Wege zu gehen.",
  "Liebe ist ... wenn man für die Jugendliebe nach 50 Jahren noch mehr empfindet als mit 17.",
  "Liebe ist ... das Gefühl, wenn du mich anschaust.",
  "Liebe ist ... wenn man hunderte Zitate über Liebe liest und keiner das zusammenfassen kann was man fühlt.",
  "Liebe ist ... wenn Mann die auch die Schwangerschaftsstreifen liebt.",
  "Liebe ist ... wenn sie im Krankenhaus beiihm schläft, um bei ihm zu sein.",
  "Liebe ist ... gaaanz weit zu fahren, um ihn im Krankenhaus zu besuchen.",
  "Liebe ist ... einen kleinen Bruder zum Anhimmeln zu haben.",
  "Liebe ist ... manchmal das größte Geheimnis.",
  "Liebe ist ... für einander dazu sein.",
  "Liebe ist ... das Gefühl, wenn du zu mir herüber blickst.",
  "Liebe ist ... Dich zuspüren ohne bei dir zu sein.",
  "Liebe ist ... eine Umarmung die nie endet.",
  "Liebe ist ... das schönste Gefühl, dass ein Mensch spühren kann.",
  "Liebe ist ... schön wenn man sie hat, aber das schlimmste, wenn man sich nach ihr sehnt.",
  "Liebe ist ... wenn Er spät von der Arbeit kommt und Sie auf Ihn gewartet und liebevoll gekocht hat .",
  "Liebe ist ... eine gemeinsame Wohnung zu haben.",
  "Liebe ist ... da wo dein Herz zuhause ist.",
  "Liebe ist ... wenn die Frau es gerne sieht wenn der Mann mit seinem Tablet spielt.",
  "Liebe ist ... dem Anderen auch Verzeihen zu können.",
  "Liebe ist ... die Zahnpastatube nicht in der Mitte zu drücken.",
  "Liebe ist ... überall möglich, auch im Internet.",
  "Liebe ist ... so einmalig wie ein Sonnenaufgang.",
  "Liebe ist ... gegenseitiges Verständnis, Vergebung, Rücksicht und Rückhalt in allen Lebenslagen.",
  "Liebe ist ... sich immer wieder neu in die selbe Person zu verlieben.",
  "Liebe ist ... wenn Sie ihm einfach so sexy Fotos schickt.",
  "Liebe ist ... auch mal das zu machen was einem selber nicht gefällt.",
  "Liebe ist ... ist einfach das schönste der Welt.",
  "Liebe ist ... nur mit dem anderen komplett zu sein.",
  "Liebe ist ... Bier in großen Mengen.",
  "Liebe ist ... wenn man das ganze leben mit dem bestem Menschen der Welt verbringen kann.",
  "Liebe ist ... morgens aufzuwachen und festzustellen, daß es kein Traum war.",
  "Liebe ist ... iebe ist, wenn er dir sein Shirt gibt, weil dir kalt ist.",
  "Liebe ist ... mehr als Chemie im Kopf.",
  "Liebe ist ... sich gegenseitig zu stärken.",
  "Liebe ist ... einfach DU.",
  "Liebe ist ... wenn es keinen Hunger, keine Kriege und keinen Kapitalismus mehr gibt.",
  "Liebe ist ... eine sinnliche Massage.",
  "Liebe ist ... jemanden trotz seiner Schwächen zu lieben.",
  "Liebe ist ... wenn Sie sich Fesseln lässt.",
  "Liebe ist ... Freundschaft.",
  "Liebe ist ... Heiß.",
  "Liebe ist ... Wenn man die ganze zeit nur an die eine Person denkt.",
  "Liebe ist ... das Glück des anderen über sein eigenes zu stellen.",
  "Liebe ist ... eine 50/50 Chance, entweder du gewinnst oder du verlierst alles.",
  "Liebe ist ... was liebe tut.",
  "Liebe ist ... etwas unfassbar Besonderes, für jeden auf eine andere Art und Weise.",
  "Liebe ist ... ein ich, das ein du sucht.",
  "Liebe ist ... wenn man seinen partner akzeptiert wie er ist.",
  "Liebe ist ... wenn es einen trifft wie ein Blitz.",
  "Liebe ist ... wenn er ihr Auto fahren darf.",
  "Liebe ist ... auf sein Herz zu hören.",
  "Liebe ist ... an sich selbst zu glauben.",
  "Liebe ist ... das leben geniessen.",
  "Liebe ist ... was mir gefällt.",
  "Liebe ist ... Freunde zu haben, die einen so lieb haben ,wie man ist.",
  "Liebe ist ... spaß zu haben wie kleine kinder.",
  "Liebe ist ... einfach cool.",
  "Liebe ist ... der Weg in eine gemeinsame Vollendung.",
  "Liebe ist ... auf den anderen zu warten.",
  "Liebe ist ... nicht aufzugeben, sondern zu kämpfen.",
  "Liebe ist ... auf jemand warten wenn es länger dauert.",
  "Liebe ist ... alle diese Sprüche zu lesen um die richtigen Worte zu finden.",
  "Liebe ist ... wenn man Tag für Tag, jede sekunde, an den anderen denken muss.",
  "Liebe ist ... wenn es wie am ersten Tag kribbelt.",
  "Liebe ist ... beim Aufwachen festzustellen, dass es kein Traum war.",
  "Liebe ist ... Nettigkeiten zu erwidern.",
  "Liebe ist ... Nettigkeiten zu erwidern.",
  "Liebe ist ... wie ein fluss als sanfter quell geboren wird zum tiefen strom.",
  "Liebe ist ... das Einzige was wir anderen geben können ohne es selbst zu haben.",
  "Liebe ist ... ein gemeinsamer Urlaub im kleinen blauen Corsa.",
  "Liebe ist ... mit dem Fahrrad zur Arbeit fahren, damit sie das Auto benutzen kann.",
  "Liebe ist ... einen Punkt zu finden, Nicht nur Kommas.",
  "Liebe ist ... alles zu erdulden.",
  "Liebe ist ... immer noch zu hoffen.",
  "Liebe ist ... in jeder Lage zu glauben.",
  "Liebe ist ... den anderen zu ertragen.",
  "Liebe ist ... sich nicht über Ungerechtigkeit wohl aber an der Wahrheit zu freuen.",
  "Liebe ist ... dem anderen nichts nachzutragen.",
  "Liebe ist ... Verbitterung nicht zuzulassen.",
  "Liebe ist ... nicht den eigenen Vorteil zu suchen.",
  "Liebe ist ... sich in jeder Situation taktvoll zu verhalten.",
  "Liebe ist ... nicht eingebildet.",
  "Liebe ist ... sich nicht selber in den Mittelpunkt stellen.",
  "Liebe ist ... Geduld mit dem anderen zu haben.",
  "Liebe ist ... dem andern freundlich zu begegnen.",
  "Liebe ist ... einen Mann an deiner Seite zu haben.",
  "Liebe ist ... ein Kuss im Regen.",
  "Liebe ist ... wie Wind, du spürst sie nicht,aber du spürst sie!.",
  "Liebe ist ... zu seinem Partner zu stehen.",
  "Liebe ist ... Egal ob Mann und Mann oder Frau und Frau.",
  "Liebe ist ... nicht zu beschreiben.",
  "Liebe ist ... auch im Streit Ich liebe Dich sagen zu können.",
  "Liebe ist ... Freunde des Partners zu akzeptieren.",
  "Liebe ist ... wenn man sich zu Hause fühlt.",
  "Liebe ist ... wenn er dir sein einziges Pizzastückchen für die Mittagspause schenkt.",
  "Liebe ist ... nicht nur auf das äussere zu schauen.",
  "Liebe ist ... auch in schlechten Zeiten zusammen stehen.",
  "Liebe ist ... wenn aus zwei Hälfen ein Ganzes wird.",
  "Liebe ist ... ein ICH, das ein DU sucht, um ein WIR zu werden.",
  "Liebe ist ... kein Gefühl, sondern ein Bio-Chemischer-Cocktail aus Dopamin, Serotonin, Oxytocin und Adrenalin.",
  "Liebe ist ... nur zu zweit möglich.",
  "Liebe ist ... ist zu wissen, dass jemand da ist.",
  "Liebe ist ... wenn du die mängel deines partners ignorierst.",
  "Liebe ist ... ihr den Rücken zu kraulen.",
  "Liebe ist ... der sommer im herzen.",
  "Liebe ist ... dem anderen das Gute gönnen.",
  "Liebe ist ... wenn er sich sorgen macht, ob du etwas für die mittagspause eingepackt hast.",
  "Liebe ist ... mehr als nur ein ich liebe dich.",
  "Liebe ist ... wenn man die Nähe spürt ohne zusammen zu sein.",
  "Liebe ist ... bedingungslose Annahme.",
  "Liebe ist ... wenn man sieht das er der richtige ist.",
  "Liebe ist ... wie ein Tag am Meer.",
  "Liebe ist ... immer füreinander da zu sein.",
  "Liebe ist ... mit dem Herzen zu schauen und nicht mit den Augen.",
  "Liebe ist ... ihm zu sagen, dass du auf einen Besuch von ihm gehofft hast.",
  "Liebe ist ... Ein Nike ohne Air, Ein Teddy ohne Bär , Win Dusch ohne das , Sonne ohne Stich so wäre freundschaft ohne dich.",
  "Liebe ist ... Eine Berührung im Leben aber eine Große Herausvorderung.",
  "Liebe ist ... die Fehler des anderen zu übersehen.",
  "Liebe ist ... unbeschreiblich schön und unersetzbar.",
  "Liebe ist ... Leidenschaft.",
  "Liebe ist ... Wir Zwei Beide.",
  "Liebe ist ... schmerzhaft.",
  "Liebe ist ... Überall zu finden.",
  "Liebe ist ... alles.",
  "Liebe ist ... dass du mich auch mal am A***h lecken kannst.",
  "Liebe ist ... wenn treu sein Spaß macht.",
  "Liebe ist ... Schmerz und Schmerz ist Liebe.",
  "Liebe ist ... wenn das alter keine rolle spielt.",
  "Liebe ist ... einfach das wunderschönste und unbeschreiblichste Gefühl der Welt.",
  "Liebe ist ... wenn zwei sich küssen und beide Lächeln müssen weil sie ihr Glück nicht fassen können.",
  "Liebe ist ... wenn man dünn pfiff bekommt.",
  "Liebe ist ... manchmal traurig, oft das Schönste, aber immer das wichtigste im Leben.",
  "Liebe ist ... wertvoller als jeder Besitz.",
  "Liebe ist ... Musik.",
  "Liebe ist ... trotz Entfernung sich dem Partner nahe zu fühlen.",
  "Liebe ist ... wenn man nicht schlafen kann, weil die Realität schöner ist als der Traum.",
  "Liebe ist ... geduldig und gütig.",
  "Liebe ist ... wenn man sich blind versteht.",
  "Liebe ist ... wenn Sie mit Ihm Achterbahn fährt.",
  "Liebe ist ... ein Flutlicht in tiefster Dunkelheit.",
  "Liebe ist ... Nicht nur zu wissen das man geliebt wird.",
  "Liebe ist ... wenn man mit dem Herzen sieht und den anderen mit all seinen Fehlern akzeptiert.",
  "Liebe ist ... das schönste Gefühl das es gibt.",
  "Liebe ist ... wenn aus du und ich wir wird.",
  "Liebe ist ... wissen er wacht über sie.",
  "Liebe ist ... seine Bedürfnisse zurückzustellen weil man möchte dass der Andere glücklich ist.",
  "Liebe ist ... gerade die Ecken und Kanten des anderen zu kennen und anzuerkennen.",
  "Liebe ist ... geben und nehmen ohne abzuwägen.",
  "Liebe ist ... wie ein Sechser im Lotto.",
  "Liebe ist ... nur mit Problemen verbunden.",
  "Liebe ist ... (Love is) a very deep friendship.",
  "Liebe ist ... wenn man sich den Kopf zerreisst.",
  "Liebe ist ... wenn man sich vermisst.",
  "Liebe ist ... auch in schlechten Zeiten zusammen stehen.",
  "Liebe ist ... ein kissen das du bei dir hast.",
  "Liebe ist ... seinem Schatz auch im Sommer Weihnachtsplätzchen zu backen.",
  "Liebe ist ... wenn man sich nach 24 Jahren wieder sieht und das Gefühl hat angekommen zu sein.",
  "Liebe ist ... wie einander vertrauen.",
  "Liebe ist ... nicht kompliziert.",
  "Liebe ist ... bedingungslos.",
  "Liebe ist ... ein Leuchtturm auch im stärksten Sturm.",
  "Liebe ist ... wie eine Droge.",
  "Liebe ist ... Entweder sie zeigt Dir das Paradies oder sie bringt Dich um.",
  "Liebe ist ... geben und nehmen ohne abzuwägen.",
  "Liebe ist ... reden ohne Worte.",
  "Liebe ist ... Zu riskieren Was Man am ende bitter Bereuen würde.",
  "Liebe ist ... Wie auf einen berg steigen.",
  "Liebe ist ... aufeinander zu warten.",
  "Liebe ist ... wenn du nicht von der erde sondern von einem ganz besonderen menschen angezogen wrist.",
  "Liebe ist ... der erste kuss.",
  "Liebe ist ... fliegen.",
  "Liebe ist ... Sich anlehnen.",
  "Liebe ist ... wie ein Vulkan der in die brodelt doch manchmal oder oft wirst du merken das er erlischt.",
  "Liebe ist ... schöne momente mit den jedigen zuverbringen,den man liebt.",
  "Liebe ist ... auch in einem Streit fürsorglich zu sein.",
  "Liebe ist ... einfach da.",
  "Liebe ist ... Sie existiert einfach und ist das schönste Gefühl das es gibt.",
  "Liebe ist ... Keine Angst vor morgen und der Zukunft zu haben.",
  "Liebe ist ... wie Toilettenpapier, erst wenn sie fehlt merkt man wie wichtig sie ist.",
  "Liebe ist ... das was ich für Dich empfinde.",
  "Liebe ist ... wenn einer den anderen komplett macht.",
  "Liebe ist ... das vertrauen zwischen zwei Menschen.",
  "Liebe ist ... wenn er auch nach 10 Jahren noch ein Feuer in dir entfachen kann.",
  "Liebe ist ... Füreinander da zu sein.",
  "Liebe ist ... unbeschreiblich.",
  "Liebe ist ... ein wenn dein Partner gleichzeitig ein guter freund ist dem du vertraust und alles erzählen kannst.",
  "Liebe ist ... ein Gefühl das man nicht beschreiben kann.",
  "Liebe ist ... Zusammen bleiben zu wollen auch wenn alles schief geht.",
  "Liebe ist ... Sich die Nacht um die Ohren zu schlagen nur damit die kleinen mit einem lächeln einschlafen.",
  "Liebe ist ... Wenn du ihn an siehst und weißt, dass es der für dich schönste Mensch der Welt ist.",
  "Liebe ist ... Sowohl innerlich als auch äußerlich.",
  "Liebe ist ... wenn man einander blind vertraut.",
  "Liebe ist ... wenn man auch nach 9 Jahren noch die Stunden bis zum Wiedersehen zählt.",
  "Liebe ist ... mit den Fehlern des Anderen zu leben.",
  "Liebe ist ... wenn du ihm vertraust und wenn du ihm noch eine zweite chance gibst.",
  "Liebe ist ... wenn man sich in seiner nähe wohlfühlt.",
  "Liebe ist ... nicht nur ein Wort. Liebe ist das Gefühl eines Menschen, von jemandem gebraucht zu werden, der genauso empfindet.",
  "Liebe ist ... ihn so sehr zu vermissen.",
  "Liebe ist ... zu ihm fahren, eine gute nacht wünschen.",
  "Liebe ist ... ihn Küssen und nach hause fahren.",
  "Liebe ist ... in seinen arme auf zu wachen und das Gefühl zu haben nichts u.",
  "Liebe ist ... die schönste Droge der Welt? den diese ist unbeschreiblich.",
  "Liebe ist ... nich begreifbar.",
  "Liebe ist ... gemeinsam zu rocken.",
  "Liebe ist ... wenn man nach Jahren immer noch liebt wie am ersten Tag.",
  "Liebe ist ... das schönste Gefühl ever diggah aber auch manchmal eine bittere entäuschung :s.",
  "Liebe ist ... Was ihr daraus macht!!.",
  "Liebe ist ... Wenn du weißt, was für ein Idiot er ist und trotzdem bei ihm bleibst.",
  "Liebe ist ... jemanden zu lieben, obwohl man ihn kennt.",
  "Liebe ist ... schande.",
  "Liebe ist ... mehr als nur ein hallo es ist zusagen ich liebe dich für immer.",
  "Liebe ist ... wärme.",
  "Liebe ist ... mit einem Lächeln auf den Lippen einzuschlafen.",
  "Liebe ist ... wenn einem der andere wichtige ist als man selbst.",
  "Liebe ist ... wenn er dir einen Heiratsantrag macht.",
  "Liebe ist ... die schönste Krankheit der Welt! - Da müssen immer gleich zwei ins bett.",
  "Liebe ist ... Verständnis, Vergebung, Rücksicht und Rückhalt in allen Lebenslagen.",
  "Liebe ist ... wie eine Schachtel Pralinen, voller vielfalt und voller Freude.",
  "Liebe ist ... wenn man bereit ist alles für die Hauptrolle in seinem Leben zu geben.",
  "Liebe ist ... was besonderes mann kan ihn vertrauen man liebt ihn so wie er ist das ist liebe.",
  "Liebe ist ... verzeien auch wenn es weh tut.",
  "Liebe ist ... die stärkste Macht.",
  "Liebe ist ... wenn die bezihung auch one sex klapt.",
  "Liebe ist ... wenn aus zwei drei werden.",
  "Liebe ist ... du und ich.",
  "Liebe ist ... pures vertrauen.",
  "Liebe ist ... das Beste, was dir passieren kann.",
  "Liebe ist ... sich kopfüber mit dir in die Tiefe zu stürzen.",
  "Liebe ist ... mehr als nur ein Ich liebe dich.",
  "Liebe ist ... auch in schweren zeiten für einander da zu sein.",
  "Liebe ist ... wenn man morgens aufwacht und es kribbelt im Bauch wenn man den Partner sieht.",
  "Liebe ist ... wenn die Entfernung keine Rolle spielt.",
  "Liebe ist ... wenn du mit jemandem alles anvertrauen kannst uund er immer für dich da ist.",
  "Liebe ist ... jemanden so sehr zu mögen, dass man ihn schon vermisst, wenn er aus der Tür geht.",
  "Liebe ist ... geduldig.",
  "Liebe ist ... wenn man lächelt ohne Grund.",
  "Liebe ist ... die Sonne zuspüren, obwohl es regnet!.",
  "Liebe ist ... den Partner trotz seiner Macken und Fehler zu lieben.",
  "Liebe ist ... ein nie endendes Labyrinth.",
  "Liebe ist ... Spaß an der Treue.",
  "Liebe ist ... wenn du nur mit ihm tanzen willst und der Takt dabei keine Rolle spielt.",
  "Liebe ist ... einfach unbeschreiblich.",
  "Liebe ist ... mehr als nur Sympathie.",
  "Liebe ist ... eine entzückend starke Anziehungskraft zweier Menschen und Verlangen, das niemals gestillt werden kann.",
  "Liebe ist ... was uns verbindet.",
  "Liebe ist ... einen VW Bus zu besitzen.",
  "Liebe ist ... das Gefühl, wenn man verwirrt ist, enttäuscht und gleichzeitig super glücklich.",
  "Liebe ist ... gemeinsam gegen den Rest der Welt.",
  "Liebe ist ... auch wenn die Sonne unter geht, denn anderen zu sehen.",
  "Liebe ist ... an den anderen Menschen mehr zu denken als an dich selbst.",
  "Liebe ist ... Zukunftsmusik.",
  "Liebe ist ... königlich.",
  "Liebe ist ... aus der Hölle den Himmel zu machen.",
  "Liebe ist ... zusammen am Telefon einschlafen.",
  "Liebe ist ... die Kraft,gebrochene Herzen zu heilen.",
  "Liebe ist ... dem anderen von seinem Glück abgeben.",
  "Liebe ist ... du.",
  "Liebe ist ... wenn man bei seinem Partner der glücklichste Mensch auf Erden ist und sich wünscht nie wieder gehen zu müssen.",
  "Liebe ist ... den anderen so zu sehen, wie Gott ihn gemeint haben könnte.",
  "Liebe ist ... einen Menschen gehen zu lassen damit er sieht, wie sehr er von Dir geliebt wird.",
  "Liebe ist ... Ihr auch in der Ferne treu zu bleiben.",
  "Liebe ist ... ein lächeln auf den lippen zu haben.",
  "Liebe ist ... wenn du den f´jenigen nur glücklich sehen willst.",
  "Liebe ist ... eine Magiesche Aura.",
  "Liebe ist ... Den Abschiedskuß vom Morgen, noch den ganzen Tag auf den Lippen zu spüren.",
  "Liebe ist ... ein für andere unsichtbares Wunder zu sehen.",
  "Liebe ist ... ihre kalten Füße zu wärmen.",
  "Liebe ist ... wenn man vergisst,wo das gehirn ist.",
  "Liebe ist ... aufeinander aufzupassen.",
  "Liebe ist ... wenn zwei Herzen wie eins schlagen.",
  "Liebe ist ... sich zusammen ihre lieblingssendung anzusehen.",
  "Liebe ist ... wenn man an eine Person mehr denkt, als an sich selbst.",
  "Liebe ist ... wenn er schon Stunden vorher zum Flughafen fährt um die Ankunft nicht zu verpassen.",
  "Liebe ist ... wenn Momente Ewigkeit werden.",
  "Liebe ist ... einfach die schönste Harmonie.",
  "Liebe ist ... morgens aufzuwachen und festzustellen, dass es kein traum war.",
  "Liebe ist ... wenn man weiß, wer der andere ist.",
  "Liebe ist ... gemeinsam auf die Rennstrecke zu gehen.",
  "Liebe ist ... das was zerbricht wenn aus Eifersucht eine Leidenschaft wird die mit Eifer sucht und dabei Leiden schafft.",
  "Liebe ist ... wie selbstverständlich die Sätze , jetzt du Schatz Achso, ja, ähhh des anderen zu vollenden.",
  "Liebe ist ... wenn du an diesen bestimmten Menschen denkst, ohne über ihn nachzudenken!.",
  "Liebe ist ... sich gegenseitig durch die dunkelsten Stunden zu tragen.",
  "Liebe ist ... wenn man immer an sie denken muss.",
  "Liebe ist ... über jeden Zweifel erhaben.",
  "Liebe ist ... nicht nur am valentinstag der liebsten was zu schenken.",
  "Liebe ist ... der halt zweier Menschen.",
  "Liebe ist ... Treu zu bleiben.",
  "Liebe ist ... Ihn auch mal auf den Schoß zu nehmen.",
  "Liebe ist ... schwierig, aber schön.",
  "Liebe ist ... wenn man ihn schon vermisst, bevor er die Haustüre verlässt.",
  "Liebe ist ... nicht nur an das eine zu denken.",
  "Liebe ist ... Dopaminvergiftung.",
  "Liebe ist ... der Person zuzuhören.",
  "Liebe ist ... ein Vertrag fürs Leben.",
  "Liebe ist ... sich einfach gut zu verstehen.",
  "Liebe ist ... der beste Freund zu sein.",
  "Liebe ist ... zusammen nichts zu tun - ohne Langeweile.",
  "Liebe ist ... vier Hände, zwei Herzen, ein Takt.",
  "Liebe ist ... wenn aus Ich und Du ein Wir wird.",
  "Liebe ist ... ein Gefühl.",
  "Liebe ist ... wenn er ihre Phantasien mitträumt.",
  "Liebe ist ... in seinen Armen einzuschlafen und von seinen Küssen geweckt zu werden.",
  "Liebe ist ... wie ein magnet.",
  "Liebe ist ... ein so akzepzieren wie er ist.",
  "Liebe ist ... ihre Gebote zu akzeptieren, bedingungslos.",
  "Liebe ist ... Überraschungen weg zu lassen, die sie nicht mag .",
  "Liebe ist ... ihr beim Tanzen nicht auf den Fuß zu treten.",
  "Liebe ist ... ihr am Auto sofort defekte Glühlampen zu wechsel.",
  "Liebe ist ... was dich reicher macht, wenn du sie weiter gibst.",
  "Liebe ist ... wenn er gut gelaunt bleibt wenn sie zickt.",
  "Liebe ist ... das beste auf der welt.",
  "Liebe ist ... wenn man jemanden eine Ohrfeige verpassen möchte und ihn gleichzeitig küssen will.",
  "Liebe ist ... dreisamkeit.",
  "Liebe ist ... eine Ballonfahrt zu machen.",
  "Liebe ist ... wundervoll.",
  "Liebe ist ... manchmal verdammt schwer .",
  "Liebe ist ... wenn jeder Tag etwas besonders ist.",
  "Liebe ist ... sich auch zu Weihnachten etwas zu schenken, obwohl man sagte: Schatz, wir schenken uns dieses mal nichts.",
  "Liebe ist ... wenn man zu Weihnachten den Teig gemeinsam mit der Herzform aussticht.",
  "Liebe ist ... wenn man verschiedene Situationen mit einer 1+ meistert.",
  "Liebe ist ... mit ihm den Sternenhimmel anzuschauen.",
  "Liebe ist ... eine Seifenblase, die niemals platzt.",
  "Liebe ist ... eine Salbe für die Seele.",
  "Liebe ist ... Herzblut.",
  "Liebe ist ... Alt und Neu zugleich.",
  "Liebe ist ... nicht mehr allein sein.",
  "Liebe ist ... Geduldt.",
  "Liebe ist ... mit und ohne Kompromisse.",
  "Liebe ist ... mehr zu geben als zu bekommen.",
  "Liebe ist ... wenn dein Herz plötzlich bei dem anderen ist.",
  "Liebe ist ... etwas zu tun ohne einbisschen Verstand.",
  "Liebe ist ... unvergänglich.",
  "Liebe ist ... ein Gefühl für die Ewigkeit.",
  "Liebe ist ... die beste Droge überhaupt.",
  "Liebe ist ... wenn man jemanden mehr mag als man sollte.",
  "Liebe ist ... Hoffen und Wünschen.",
  "Liebe ist ... Warten.",
  "Liebe ist ... wenn man sich mehr Chancen gibt als man sollte.",
  "Liebe ist ... die schönste Muksik.",
  "Liebe ist ... stärker als alles Andere.",
  "Liebe ist ... Eine tiefgehende Verbindung.",
  "Liebe ist ... Etwas, was einem am Leben hält.",
  "Liebe ist ... Ein geschenk von Gott.",
  "Liebe ist ... Freundschaft.",
  "Liebe ist ... ein himmlisches Geschenk.",
  "Liebe ist ... wenn du ohne ihn nicht denken kannst.",
  "Liebe ist ... sein Atem im Nacken.",
  "Liebe ist ... wenn er dein Herzschlag ist.",
  "Liebe ist ... was dich lächeln lässt wenn du müde bist.",
  "Liebe ist ... wenn daraus Leben wird.",
  "Liebe ist ... in guten wie in schlechten Zeiten.",
  "Liebe ist ... zu hören, wie ihr Herz schneller schlägt.",
  "Liebe ist ... was man teilt.",
  "Liebe ist ... wenn ich ihr aus Unachtsamkeit wehgetan habe und mich dafür schäme.",
  "Liebe ist ... wenn man sich gegenseitig glücklich macht und Kontroversen ausblendet.",
  "Liebe ist ... das Verlangen nach dieser einen Person, ohne Abstriche.",
  "Liebe ist ... es dem anderen auch zu verzeihen , wenn es schwer fällt.",
  "Liebe ist ... wenn sein Besuch die beste Medizin ist.",
  "Liebe ist ... wenn der tausendste Kuss sich noch wie der erste anfühlt.",
  "Liebe ist ... von kecks zu kecks zu wandern und sich gegenseitig zu krümmeln.",
  "Liebe ist ... der beste Freund des anderen zu sein.",
  "Liebe ist ... nicht nur gesucht werden.",
  "Liebe ist ... alles von ihm zu kennen und trotzdem nicht genug von ihm zu bekommen.",
  "Liebe ist ... wenn dir ihre Augen sagen, wie Glücklich sie ist.",
  "Liebe ist ... diskret wegschauen, wenn sie auf der Waage steht.",
  "Liebe ist ... wenn aus einem ich und du ein wir wird.",
  "Liebe ist ... sie immer probieren zu lassen.",
  "Liebe ist ... wenn aus zwei, drei werden.",
  "Liebe ist ... das unmügliche wahr werden zu lassen.",
  "Liebe ist ... wie Schokolade.",
  "Liebe ist ... Vertrauen.",
  "Liebe ist ... wenn der andere das bester Parfum ist.",
  "Liebe ist ... schön, aber auch schmerzhaft.",
  "Liebe ist ... wie eine Reise durch ein fremdes Land.",
  "Liebe ist ... verlieben,vergessen,verzeihen,sichhassen,verlassen und doch unzertrennlich sein.",
  "Liebe ist ... so süß wie Nutella.",
  "Liebe ist ... wenn man nach einem Streit noch sagen kann Ich liebe dich.",
  "Liebe ist ... Hasi und Mausi.",
  "Liebe ist ... sie auch zu vermissen wenn sie neben dir sitzt.",
  "Liebe ist ... hat unendlich viele Facetten.",
  "Liebe ist ... wenn dein Partner dein Lächeln sieht und sofort weis ob es echt ist oder nur geschauspielert.",
  "Liebe ist ... wenn man ein krippeln in Bauch hatt das ist das zeichen das du für dein Menschen Gefühle empfindest und immer zusammen halten auch in schlechten und in guten zeiten.",
  "Liebe ist ... der richtige Mann an ihrer Seite zu sein.",
  "Liebe ist ... nicht nur Geschlechter übergreifend.",
  "Liebe ist ... wenn man nach langer Zeit immer noch Herzklopfen von ner einfachen Umarmung bekommt.",
  "Liebe ist ... alles im Leben miteinander zu teilen.",
  "Liebe ist ... wenn du weisst,das Sie die richtige in deinem Leben ist.",
  "Liebe ist ... wenn man sich ohne Worte verständigen kann.",
  "Liebe ist ... wenn man sie verlässt ,um sie glücklich zu machen.",
  "Liebe ist ... wenn man nach 50 Jahren immer noch seinen Kaffee gemacht bekommt.",
  "Liebe ist ... wenn man gemeinsam genug Energie hat um ein großes Ziel zu erreichen.",
  "Liebe ist ... einfach DU selbst sein zu können.",
  "Liebe ist ... mit einem Blümchen überrascht zu werden, wenn man es am wenigsten erwartet.",
  "Liebe ist ... wenn sich beide auf das Wochenende freuen und sich wieder in die Arme nehmen.",
  "Liebe ist ... wenn er ihren Namenstag nicht vergisst.",
  "Liebe ist ... auch in schlechten Zeiten immer zusammenzuhalten.",
  "Liebe ist ... wenn man nur noch an den anderen denken kann.",
  "Liebe ist ... etwas was man unbewusst sucht und findet.",
  "Liebe ist ... wenn man denn anderen vertraut.",
  "Liebe ist ... wenn man es spürt.",
  "Liebe ist ... für immer zusammen zusein.",
  "Liebe ist ... wenn man in den Armen des Partners lachen und weinen kann.",
  "Liebe ist ... alles, was im Leben zählt.",
  "Liebe ist ... nicht nur ein Wort.",
  "Liebe ist ... Leidenschaft.",
  "Liebe ist ... eine Freundschaft, die in Flammen steht.",
  "Liebe ist ... so viele schöne Erinnerungen zu haben, dass man die weniger guten schon fast vergisst.",
  "Liebe ist ... ihm ein lächeln ins Gesicht zu zaubern.",
  "Liebe ist ... gemeinsam durch dick und dünn zu gehen.",
  "Liebe ist ... wenn man die Unendlichkeit spüren kann.",
  "Liebe ist ... der wahre Sinn des Lebens.",
  "Liebe ist ... zuneigung und respekt.",
  "Liebe ist ... es ihr auf 100 verschiedene Arten zu zeigen, ohne es auszusprechen.",
  "Liebe ist ... von wärme erfüllt zu werden, wenn ich an Dich denke.",
  "Liebe ist ... nichts anderes, als Trauer, Neid und Hass.",
  "Liebe ist ... wen man jemand hat mit dem man durch gute und schlechte zeiten gehen kann.",
  "Liebe ist ... wie Macht, wer sie missbraucht wird nie glücklich.",
  "Liebe ist ... für immer zusammen zusein.",
  "Liebe ist ... 80 km in 20 minuten zu schaffen.",
  "Liebe ist ... das schöneste auf der ganzen Welt.",
  "Liebe ist ... alles für einen zu tun.",
  "Liebe ist ... wie ein Einhorn.",
  "Liebe ist ... wenn er seine eigene Praxis hintenanstellt, um ihr beim Yoga in den Kopfstand zu helfen.",
  "Liebe ist ... wenn aus einem du und ich ein wir entsteht.",
  "Liebe ist ... Das einzige was wächst, wenn man es teilt.",
  "Liebe ist ... nicht zu verzweifeln weil du immer da bist.",
  "Liebe ist ... zu lächeln bei dem gedanken an dich.",
  "Liebe ist ... sich nahe zu sein trotz grosser Entfernung.",
  "Liebe ist ... etwas gefunden zu haben wonach man nie gesucht hat.",
  "Liebe ist ... wenn Man(n) wieder die Füße der Liebsten verwöhnen darf.",
  "Liebe ist ... nie wieder ohne den anderen sein zu wollen.",
  "Liebe ist ... wenn man vor Einsamkeit am liebsten sterben würde.",
  "Liebe ist ... unendlich.",
  "Liebe ist ... das schönste Gefühl der Welt, welches zerbricht, wenn Eifersucht im Spiel ist.",
  "Liebe ist ... wenn man den anderen immer vermisst.",
  "Liebe ist ... sich auch mal selbst an den Pranger zu stellen.",
  "Liebe ist ... wenn man es spürt.",
  "Liebe ist ... immer dem Partner vertrauen zu können!.",
  "Liebe ist ... wenn er für sie auf seine Spielkonsole verzichtet.",
  "Liebe ist ... der Sinn des Lebens.",
  "Liebe ist ... wenn du Angst hast ihn zu verlieren und dich änderst.",
  "Liebe ist ... teil eines Wunder zu sein.",
  "Liebe ist ... so unglaublich und unbeschreiblich schön wie Du.",
  "Liebe ist ... von wärme erfüllt zu werden, wenn ich an Dich denke.",
  "Liebe ist ... lecker.",
  "Liebe ist ... die schönste Sucht der Welt.",
  "Liebe ist ... ein Abenteuer zu zweit.",
  "Liebe ist ... gemeinsam aufzuräumen, auch wenn beide unordentlich sind.",
  "Liebe ist ... wenn Er sich nicht meldet, Sie aber weiss das Er an sie denkt.",
  "Liebe ist ... wenn Du nicht einschlafen kannst, weil die Realität im Moment schöner ist, als ein Traum es jemals sein kann.",
  "Liebe ist ... den anderen so zu nehmen, wie er ist.",
  "Liebe ist ... manchmal ein Traum un leider manchmal Grauen.",
  "Liebe ist ... wenn es dann doch anders kommt, als man es für möglich gehalten hat.",
  "Liebe ist ... wenn man nicht von einander weg kommt.",
  "Liebe ist ... Teamarbeit.",
  "Liebe ist ... sich in seiner Gegenwart Überall zuhause zu fühlen.",
  "Liebe ist ... wenn ER zu IHR sagt DU bist das besser was mir passiert ist.",
  "Liebe ist ... mit dem Herzen zu denken.",
  "Liebe ist ... hart und schmerzhaft.",
  "Liebe ist ... dein Leben.",
  "Liebe ist ... wenn man für immer sagen kann Ich Liebe Dich.",
  "Liebe ist ... das beste, was einem Menschen im Leben je passieren kann.",
  "Liebe ist ... wenn Sie und Er sich bei der KLJB kennen lernen.",
  "Liebe ist ... auf jemanden zu warten auch wenn man nicht weiß wann er zurückkommt.",
  "Liebe ist ... wenn man sich selbst Lieben kann.",
  "Liebe ist ... wenn man nie vergisst wie wichtig diese person für einen ist.",
  "Liebe ist ... zu kämpfen auch wenn keine Hoffnung mehr vorhanden ist.",
  "Liebe ist ... den anderen los zulassen, wenn er frei sein will.",
  "Liebe ist ... wenn das aussehen egal ist und man sich einfach Vertraut.",
  "Liebe ist ... DA ZU SEIN WENN ALLEANDEREN GEHN.",
  "Liebe ist ... ZUWEINEN WENN ER MAL NICHTDA IST.",
  "Liebe ist ... trotz so vieler km zwischen zwei Menschen zusammen zu sein.",
  "Liebe ist ... wenn man bauchkribbeln bekommt sobald man an ihn denkt.",
  "Liebe ist ... wie der Wind. Man kann sie nicht sehen, aber fühlen.",
  "Liebe ist ... wenn man einfach mal die Ruhe vor dem anderen braucht, und doch nie genug voneinander hat.",
  "Liebe ist ... zusammen auf Berge zu wandern und nie erschöpft zu sein.",
  "Liebe ist ... zusammen das Essen zu genießen.",
  "Liebe ist ... lebenslänglich durch die welt mit dir zu gehen.",
  "Liebe ist ... wenn du mir ein Lächeln ins Gesicht zauberst wenn ich dich sehe.",
  "Liebe ist ... wenn 1+1=3 ist.",
  "Liebe ist ... gemeinsam abzutauchen.",
  "Liebe ist ... sich geborgen und verstanden zu fühlen.",
  "Liebe ist ... wenn man an seinen Liebsten denkt und damit einfach nicht aufhören kann.",
  "Liebe ist ... wenn die Oma ihren kleinen Enkel zu Besuch hat.",
  "Liebe ist ... wenn gute Freundschaft nicht ausreicht.",
  "Liebe ist ... wenn zwei Menschen wir sagen können.",
  "Liebe ist ... einfach immer an ihn zudenken egal wo er gerade ist.",
  "Liebe ist ... einen Doppelkeks zu teilen und dem anderen die Seite mit der Schokolade zu geben.",
  "Liebe ist ... die Sehnsucht den andern glücklich zu machen.",
  "Liebe ist ... wie Sonnenschein - sie wärmt Dein Herz und macht es rein.",
  "Liebe ist ... wie eine Umarmung, die Dir Geborgenheit schenkt.",
  "Liebe ist ... wie ein Blick, der Dir wieder Mut und Hoffnung schenkt.",
  "Liebe ist ... wie Musik - sie belebt und macht fröhlich.",
  "Liebe ist ... wenn ein Kuss nicht nur die Lippen berührt, sondern auch das Herz.",
  "Liebe ist ... wenn man zusammen lachen und weinen kann.",
  "Liebe ist ... so süss wie Gummibärchen.",
  "Liebe ist ... gemeinsam Steine aus dem Weg räumen.",
  "Liebe ist ... man muss es selbst fühlen um zu wissen was es ist.",
  "Liebe ist ... etwas unbeschreibliches.",
  "Liebe ist ... wenn Unterschiede keinen Unterschied machen.",
  "Liebe ist ... zu wissen, dass ER das erste ist, was man am morgen sieht.",
  "Liebe ist ... stärker als deine Macken.",
  "Liebe ist ... dich mehr zu lieben als Du Macken hast.",
  "Liebe ist ... wenn man nie vergisst wie wichtig diese person für einen ist.",
  "Liebe ist ... morgens aufzuwachen und zu wissen dass du tief in ihrem Herzen einen Platz hast.",
  "Liebe ist ... wenn er sie im Regen küsst.",
  "Liebe ist ... auch in schwierigen Momenten niemals zu vergessen, für was man kämpfen sollte.",
  "Liebe ist ... wenn man OHNE ihn nicht einschlafen kannst.",
  "Liebe ist ... wenn man beim kuscheln auf seiner Brust einschläft und er dir durch das Haar streicht.",
  "Liebe ist ... da um sie jedem zu zeigen.",
  "Liebe ist ... jede Sekunde mit ihm zu genießen.",
  "Liebe ist ... wenn man weiß, dass der andere immer da sein wird, was auch geschehen mag, wenn man den anderen während seiner Abwesenheit vermisst, ihn aber immer im Herzen trägt.",
  "Liebe ist ... auf jemanden zu warten, auch wenn man nicht weis wann er zurück kommt.",
  "Liebe ist ... füreinander da zu sein.",
  "Liebe ist ... das wunderschönste was es gibt.",
  "Liebe ist ... nicht traurig zu sein wenn ER weg Muss.",
  "Liebe ist ... schönste Gefühl der welt.",
  "Liebe ist ... wenn es Spaß macht, treu zu sein.",
  "Liebe ist ... sie im wahrsten Sinn von Kopf bis Fuss zu lieben.",
  "Liebe ist ... unergründlich.",
  "Liebe ist ... sich geborgen zu fühlen.",
  "Liebe ist ... wenn der eine für den anderen die Praline des Lebens ist.",
  "Liebe ist ... ein Wort das kein Mensch dieser Welt beschreiben kann.",
  "Liebe ist ... das Einzige und das Größte.",
  "Liebe ist ... ein auf und ein ab genauso wie im Laufrad.",
  "Liebe ist ... zu wissen, dass Dein Hallo immer an Dich denkt.",
  "Liebe ist ... miteinander zu schweigen, aber schöner ist es, miteinander zu lachen.",
  "Liebe ist ... wenn man sich immer wieder findet, nachdem man sich aus den Augen verloren hat.",
  "Liebe ist ... wenn man keinen klaren Gedanken, ausser den an Ihn mehr hat.",
  "Liebe ist ... ihn immer fest in den Armen zu halten.",
  "Liebe ist ... wenn man Sex hat.",
  "Liebe ist ... bis ans Lebendsende zusammen zu sein.",
  "Liebe ist ... sich geborgen zu fühlen.",
  "Liebe ist ... himmlisch.",
  "Liebe ist ... wenn man sich meldet ohne das es der andere erwartet.",
  "Liebe ist ... gemeinsam shoppen zu gehen ohne das er motzt.",
  "Liebe ist ... in guten und schlechten Tagen, für einander da zu sein.",
  "Liebe ist ... so kompliziert das man vergisst was hass ist.",
  "Liebe ist ... wenn man sein letzten pfennig fur ihn ausgibt.",
  "Liebe ist ... dein puzzlestück gefunden zu haben.",
  "Liebe ist ... wenn er ungefragt und kommentarlos den Riesen-Vogelschiss von ihrem Auto abwischt.",
  "Liebe ist ... Miteinander + Füreinander + Vertrauen.",
  "Liebe ist ... das Beste, was es auf der Welt gibt.",
  "Liebe ist ... das Einzige was sich verdoppelt wenn man es teilt.",
  "Liebe ist ... ihr einen Kuss auf die sü$szlig;en Füße zu geben.",
  "Liebe ist ... zu ihm nach Hause zu kommen.",
  "Liebe ist ... ohne Gott und ohne Paradies Nächstenliebe zu leben.",
  "Liebe ist ... wenn nur der Gedanke an sie/ihn dir ein Lächeln ins Gesicht zaubert.",
  "Liebe ist ... ein Jungbrunnen.",
  "Liebe ist ... das zu sehen, was andere nicht vermögen.",
  "Liebe ist ... gemeinsam die Klippen des Lebens zu umschiffen.",
  "Liebe ist ... ein immerwährender Prozess.",
  "Liebe ist ... dem anderen bedingungslos zu vertauen.",
  "Liebe ist ... für immer loslassen zu können auch wenn es noch so weh tut.",
  "Liebe ist ... ein unbeschreibliches Gefühl.",
  "Liebe ist ... das beste was man an ihm hat.",
  "Liebe ist ... wenn der eine für den anderen die Rosinen ausm Müsli pickt.",
  "Liebe ist ... Schlechte laune.",
  "Liebe ist ... wenn es sich richtig anfühlt.",
  "Liebe ist ... die EINE Person gefunden zu haben.",
  "Liebe ist ... das was Wikipedia niemals in Worte fassen könnte.",
  "Liebe ist ... sich zu zügeln bevor böse Worte fallen.",
  "Liebe ist ... manchmal einsam und allein.",
  "Liebe ist ... die größte Illusion aller Zeiten.",
  "Liebe ist ... Sie beim schlafen zu beobachten.",
  "Liebe ist ... zu fühlen.",
  "Liebe ist ... Vertauen.",
  "Liebe ist ... seinen Schatz in la Blue zu finden.",
  "Liebe ist ... um jemanden zu kämpfen, den man schon lange verloren hat.",
  "Liebe ist ... ALLES.",
  "Liebe ist ... du und ich.",
  "Liebe ist ... das Gefühl dass dich nie die wichtigsten Person in deinem leben vergessen lässt.",
  "Liebe ist ... wenn ich sag mir gehts gut und du sagts sag mir die wahrheit.",
  "Liebe ist ... unbeschreiblich , es ist das Gefühl was jeder Spühren sollte. Das Gefühl jemanden zu haben, und sie zu spühren.",
  "Liebe ist ... gemeinsam um die Wette zu schwimmen.",
  "Liebe ist ... wenn du mit ihr an deiner Seite Hulk besiegen köntest.",
  "Liebe ist ... nichts als Ärger.",
  "Liebe ist ... der grund warum ich dich liebe.",
  "Liebe ist ... den boden unter den füßen verlieren.",
  "Liebe ist ... der grund warum wir auf Erden sind.",
  "Liebe ist ... der Beginn einer wunderschönen Beziehung.",
  "Liebe ist ... wenn beide im selben Augenblick das Gleich denken.",
  "Liebe ist ... zärtlich und geduldig zu sein wenn der andere traurig ist.",
  "Liebe ist ... wenn jeder Kuss zählt.",
  "Liebe ist ... etwas was von Jahr zu Jahr größer wird.",
  "Liebe ist ... in auf eine liebe art und weise zu beruhigen, wenn ihn etwas auf die palme bringt.",
  "Liebe ist ... wenn man den Herzschlag durchs T-Shirt spührt.",
  "Liebe ist ... wenn das Leben für dich ohne den anderen unvorstellbar ist.",
  "Liebe ist ... in deinem Arm einzuschlafen und von deinen Küssen geweckt zu werden.",
  "Liebe ist ... wenn er alles versucht um seine liebste online zu sehen.",
  "Liebe ist ... wenn sie wieder zueinander finden.",
  "Liebe ist ... zu wissen,dass man alles für die andere Person aufgeben würde und sich selbst in den Hintergrund stellt.",
  "Liebe ist ... eine nicht aufzuhaltene Flut.",
  "Liebe ist ... immer an seinen Liebsten zu glauben.",
  "Liebe ist ... wenn der schönste Moment,die erste Begegnung ist.",
  "Liebe ist ... in deine Planlosigkeit Ordnung zu bringen.",
  "Liebe ist ... wenn man ohne ihn / sie nicht einschlafen kann.",
  "Liebe ist ... zu wissen was dem anderen Schmerzen bereitet ohne das er ein Wort sagen muss.",
  "Liebe ist ... auch wenn das Meer stürmisch ist immer bis zu Horizont zu schwimmen.",
  "Liebe ist ... den anderen mit allen Fehlern zu lieben.",
  "Liebe ist ... wenn die Realität schöner ist als jeder Traum.",
  "Liebe ist ... wenn zwei Seelen miteinander verschmelzen, lasse es zu.",
  "Liebe ist ... wie der Treibsand einer Düne, lasse Dich treiben.",
  "Liebe ist ... Hingabe und das höchste Glück dieser Erde, lasse es geschehen.",
  "Liebe ist ... wenn zwei Herzen zu einer Einheit werden, lasse es zu.",
  "Liebe ist ... dass unerreichbare zu verwirklichen, verwirkliche es.",
  "Liebe ist ... Zärtlichkeiten auszutauschen, tausche sie aus.",
  "Liebe ist ... wie das siebte Weltwunder, lasse das Wunder geschehen.",
  "Liebe ist ... der Austausch von Gefü;hlen, die vom Herzen kommen, erlebe sie.",
  "Liebe ist ... wie ein Zauber der Natur, lass Dich von Ihr verzaubern.",
  "Liebe ist ... die Quelle, die immer wieder zu neuem Leben erweckt, trinke von Ihr.",
  "Liebe ist ... der Nektar des Lebens, koste Ihn.",
  "Liebe ist ... so köstlich, wie der schönste Wein, geniesse Ihn.",
  "Liebe ist ... Gefü;hle auszutauschen, lasse sie zu.",
  "Liebe ist ... ein Geschenk des Himmels, nimm es an.",
  "Liebe ist ... die Melodie des Herzens.",
  "Liebe ist ... die Antwort.",
  "Liebe ist ... nach nem harten Tag nach Haus zu kommen, krank zu sein und dann ein schönes, heißes, eingelassenes Bad vorzufinden.",
  "Liebe ist ... sich jeden Tag gemeinsam über sein Kind zu freuen.",
  "Liebe ist ... ´ne Party nur für zwei.",
  "Liebe ist ... ihm g a a a n z geduldig zuzuhören.",
  "Liebe ist ... ihr mit viel Geduld das Angeln beizubringen.",
  "Liebe ist ... zwei Wohnungen gegen eine zu tauschen.",
  "Liebe ist ... zusammen mit dem Mond auf den Liebsten zu warten.",
  "Liebe ist ... zusammen in die Kantine zu gehen.",
  "Liebe ist ... zusammen einfach unschlagbar zu sein.",
  "Liebe ist ... zusammen die Seele baumeln zu lassen.",
  "Liebe ist ... zusammen baden zu gehen.",
  "Liebe ist ... zu wünschen, du wärst hier.",
  "Liebe ist ... zu wissen, was man aneinander hat.",
  "Liebe ist ... zu wissen, wann man sie besser in Ruhe lässt.",
  "Liebe ist ... zu wissen, dass er der eine unter Millionen ist.",
  "Liebe ist ... zu wissen, das er immer für einen da ist.",
  "Liebe ist ... zu winken, bis der Zug nicht mehr zu sehen ist.",
  "Liebe ist ... zu spüren, wie schwer sie es im Haushalt hat.",
  "Liebe ist ... zu Hause am schönsten.",
  "Liebe ist ... zärtliche Gedanken aufzuschreiben, damit er sie immer lesen kann.",
  "Liebe ist ... wie jeden Tag Geburtstag.",
  "Liebe ist ... wie eine unerwartete frohe Botschaft.",
  "Liebe ist ... wie eine Pflanze, die man pflegen muss.",
  "Liebe ist ... wie eine Lotterie: mal Hauptgewinn, mal Niete.",
  "Liebe ist ... wie eine Flamme, die nie verlöscht.",
  "Liebe ist ... wie ein Traum. Nur noch schöner.",
  "Liebe ist ... wie ein starker Baum. Kein Sturm kann ihr was anhaben.",
  "Liebe ist ... wie ein romantischer Tanz unter tropischem Sternenhimmel.",
  "Liebe ist ... wie ein Korb voller Glück.",
  "Liebe ist ... wie ein Glas mit zwei Strohalmen.",
  "Liebe ist ... wie ein Felsen. Das beste Fundament des Lebens.",
  "Liebe ist ... wie ein Cocktail - süß und berauschend.",
  "Liebe ist ... wichtiger als eine Beule am Auto.",
  "Liebe ist ... wenn´s einem die Füße wegreißt.",
  "Liebe ist ... wenn´s bei beiden klick macht.",
  "Liebe ist ... wenn zwei Körper die selbe Sprache sprechen.",
  "Liebe ist ... wenn zwei im Gefühl eins sind.",
  "Liebe ist ... wenn zwei Herzen zum Himmel fliegen.",
  "Liebe ist ... wenn zwei Herzen zu einem verschmelzen.",
  "Liebe ist ... wenn zwei Herzen fest verbunden sind.",
  "Liebe ist ... wenn zwei Herzen aufeinander zurasen.",
  "Liebe ist ... wenn zwei Hälften zum perfekten Ganzen werden.",
  "Liebe ist ... wenn zwei auf der gleichen Wellenlänge funken.",
  "Liebe ist ... wenn zwei am liebsten eins sind.",
  "Liebe ist ... wenn Worte überflüssig sind, weil Blicke alles sagen.",
  "Liebe ist ... wenn sogar die Wüste zu blühen beginnt.",
  "Liebe ist ... wenn sie versucht, seine Hobbys gut zu finden.",
  "Liebe ist ... wenn sie verstehen möchte, warum er so ganz anders denkt.",
  "Liebe ist ... wenn sie über seinen geschmacklichen Ausrutscher hinwegsieht.",
  "Liebe ist ... wenn sie seinen Lieblingsduft auflegt.",
  "Liebe ist ... wenn sie seine Zukunft in die Hand nimmt.",
  "Liebe ist ... wenn sie seine Gedanken lesen kann.",
  "Liebe ist ... wenn SIE sehnsüchtig auf seine Rückkehr wartet.",
  "Liebe ist ... wenn sie schon die berühmten Glocken hört.",
  "Liebe ist ... wenn sie nur noch von ihm träumt.",
  "Liebe ist ... wenn sie nur ihn - ihn- ihn im Kopf hat.",
  "Liebe ist ... wenn sie nur dir diesen Blick schenkt.",
  "Liebe ist ... wenn SIE kommt. Dann beginnt die schönste Zeit des Jahres.",
  "Liebe ist ... wenn sie ihre kalten Füße bei ihm wärmen darf.",
  "Liebe ist ... wenn sie ihn zum Anknabbern findet.",
  "Liebe ist ... wenn sie ihn in ihr Nachtgebet einschließt.",
  "Liebe ist ... wenn SIE ihn immer festhalten möchte.",
  "Liebe ist ... wenn sie ihm wenigstens den Sportteil lässt.",
  "Liebe ist ... wenn sie ihm sein Hobby noch ein bisschen versüßt.",
  "Liebe ist ... wenn sie ihm nicht immer nachräumen muss.",
  "Liebe ist ... wenn SIE ihm mehr bedeutet als ein Fußballspiel.",
  "Liebe ist ... wenn sie ihm die berühmten 3 Worte ins Ohr flüstert.",
  "Liebe ist ... wenn sie ihm das Rauchen abgewöhnt.",
  "Liebe ist ... wenn SIE einen Abend frei hat.",
  "Liebe ist ... wenn sie der Sonnenschein in deinem Leben ist.",
  "Liebe ist ... wenn sie das Telefon beschwört, damit endlich anruft.",
  "Liebe ist ... wenn sie das Auto aussuchen darf.",
  "Liebe ist ... wenn sie dafür sorgt, dass die Woche gut anfängt.",
  "Liebe ist ... wenn sie bei seiner Umarmung glatt den Boden unter den Füßen verliert.",
  "Liebe ist ... wenn sie bei ihrem Einkaufsbummel auch an ihn denkt.",
  "Liebe ist ... wenn sie ausspricht, was ihm so schwer über die Lippen kommt.",
  "Liebe ist ... wenn sie auf jeder Party für ihn der Mittelpunkt ist.",
  "Liebe ist ... wenn sie auch bei seiner 10. Runde Moorhuhnschießen nicht ausflippt.",
  "Liebe ist ... wenn Sie auch aus der Ferne an ihn denkt.",
  "Liebe ist ... wenn sie am liebsten seine Hemden trägt.",
  "Liebe ist ... wenn sich dein ganzes Leben mit einem Schlag ändert.",
  "Liebe ist ... wenn seine Blicke dich streicheln.",
  "Liebe ist ... wenn seine Berührungen süße Schauer auslösen.",
  "Liebe ist ... wenn sein Herz nur um sie kreist.",
  "Liebe ist ... wenn Papas Schulter der schönste Schlafplatz ist.",
  "Liebe ist ... wenn Papa für die Sesamstraße alles stehen und liegen lässt.",
  "Liebe ist ... wenn ohne ihn ihr Herz in Tränen schwimmt.",
  "Liebe ist ... wenn nichts zwei Menschen, die sich lieben, trennen kann.",
  "Liebe ist ... wenn mit Ihm auch ein Stück von dir geht.",
  "Liebe ist ... wenn man wünscht, die Zeit möge stehen bleiben.",
  "Liebe ist ... wenn man weiß, wo man Trost findet.",
  "Liebe ist ... wenn man weiß, dass man sich gefunden hat.",
  "Liebe ist ... wenn man sich wie im Himmel fühlt.",
  "Liebe ist ... wenn man sich über Lebenslänglich freut.",
  "Liebe ist ... wenn man sich gar nicht mehr loslassen will.",
  "Liebe ist ... wenn man sich einfach nicht trennen kann.",
  "Liebe ist ... wenn man sein Herz hergibt - und ein anderes bekommt.",
  "Liebe ist ... wenn man sein Glück fest im Arm hat.",
  "Liebe ist ... wenn man ohne den anderen den Halt verlieren würde.",
  "Liebe ist ... wenn man nur noch tanzend durch das Leben geht.",
  "Liebe ist ... wenn man nur einen Schatz hat - IHN.",
  "Liebe ist ... wenn man nicht mehr weiß, wo der eine anfängt und der andere aufhört.",
  "Liebe ist ... wenn man Mittags schon verträumt den Besen umarmt.",
  "Liebe ist ... wenn man Mittags nur Appetit auf sie hat.",
  "Liebe ist ... wenn man keine Worte mehr braucht.",
  "Liebe ist ... wenn man in seinen Armen gar nicht traurig sein kann.",
  "Liebe ist ... wenn man ihretwegen Kopf steht.",
  "Liebe ist ... wenn man ihn so richtig im Griff hat.",
  "Liebe ist ... wenn man genau weiß, was ihr zwinkern bedeutet.",
  "Liebe ist ... wenn man gar nicht mehr weiß, wie man ohne den anderen leben kann.",
  "Liebe ist ... wenn man auch mal zugibt, ich hatte Unrecht.",
  "Liebe ist ... wenn man an nichts anderes mehr denken kann.",
  "Liebe ist ... wenn man alles anschleppt, um ihre Grippe zu vertreiben.",
  "Liebe ist ... wenn Kinderaugenglanz wichtiger ist, als selbst zu glänzen.",
  "Liebe ist ... wenn jemand deinen Schlaf bewacht.",
  "Liebe ist ... wenn jemand dein Herz zum Rasen bringt.",
  "Liebe ist ... wenn jeder sich zuerst entschuldigen will.",
  "Liebe ist ... wenn jeder ihm ansieht, wie sehr er sich auf sie freut.",
  "Liebe ist ... wenn jede Umarmung so aufregend wie die erste ist.",
  "Liebe ist ... wenn ihr ein Kuss lieber ist als der schönste Nachtisch.",
  "Liebe ist ... wenn ihr die Freude vergeht, weil er fehlt.",
  "Liebe ist ... wenn ihm nicht wichtiger ist, als ein Kuss zwischendurch.",
  "Liebe ist ... wenn Herz zu Herz gefunden hat.",
  "Liebe ist ... wenn es zwischen zwei Menschen sofort funkt.",
  "Liebe ist ... wenn es PENG macht und du weißt: Sie ist es.",
  "Liebe ist ... wenn es dich trifft wie ein Blitz.",
  "Liebe ist ... wenn es bei beiden gleichzeitig einschlägt.",
  "Liebe ist ... wenn er unbedingt eine Locke von ihr für sein Portemonnaie will.",
  "Liebe ist ... wenn er SIE nie wieder loslassen möchte.",
  "Liebe ist ... wenn ER sie mal bedient.",
  "Liebe ist ... wenn er sich in jeder Situation schützend vor sie stellt.",
  "Liebe ist ... wenn er sich in ihr Herz spielt.",
  "Liebe ist ... wenn er sich immer anschleicht, um ihr den Nacken zu massieren.",
  "Liebe ist ... wenn er sich für SIE die Finger schmutzig macht.",
  "Liebe ist ... wenn er seine weiche Seite zeigt und für sie in die Saiten greift.",
  "Liebe ist ... wenn er seine Sachen auch mal selbst wegräumt.",
  "Liebe ist ... wenn er seine Augen nicht von ihr lassen kann.",
  "Liebe ist ... wenn er nur für Sie da ist.",
  "Liebe ist ... wenn er Nacht für Nacht den Kalte - Füße - Schock erträgt.",
  "Liebe ist ... wenn er mit Rosen kommt - einfach so, ohne Grund.",
  "Liebe ist ... wenn er mit ihr leidet, weil sie schlecht geträumt hat.",
  "Liebe ist ... wenn er mit Blumen sagt, wozu ihm sonst die Worte fehlen.",
  "Liebe ist ... wenn er mal selbst aufräumt.",
  "Liebe ist ... wenn er lernt sie zu verstehen.",
  "Liebe ist ... wenn er immer ihr starker Held bleibt.",
  "Liebe ist ... wenn er immer bei ihr ist, sogar im Traum.",
  "Liebe ist ... wenn er im richtigen Moment Fingerspitzen-Gefühl zeigt.",
  "Liebe ist ... wenn er ihre kalten Füße warm rubbelt.",
  "Liebe ist ... wenn er ihr zeigt, wie es um sein Herz steht.",
  "Liebe ist ... wenn er ihr Herzensretter ist.",
  "Liebe ist ... wenn er gern nach ihrer Pfeife tanzt.",
  "Liebe ist ... wenn er gar nicht anders kann - er muss ihr folgen.",
  "Liebe ist ... wenn er ganz klassisch um sie wirbt.",
  "Liebe ist ... wenn ER für SIE immer der Sieger ist.",
  "Liebe ist ... wenn er es rote Rosen regnen lässt.",
  "Liebe ist ... wenn er die Zeit vergisst, weil sie bei ihm ist.",
  "Liebe ist ... wenn er die Stunden zählt, bis sie wieder bei ihm ist.",
  "Liebe ist ... wenn er die Seiten in ihrem Tagebuch füllt.",
  "Liebe ist ... wenn er die Antwort auf ihre Gebete ist.",
  "Liebe ist ... wenn er den Grill anschmeißt, damit sie mal nicht kochen muss.",
  "Liebe ist ... wenn er dein Herz gewonnen hat.",
  "Liebe ist ... wenn er allen erzählt, was für ein Schatz sie ist.",
  "Liebe ist ... wenn einer den anderen beim Fitmachen anspornt.",
  "Liebe ist ... wenn einer den anderen auf dem Weg des Lebens stützt.",
  "Liebe ist ... wenn einen die Gefühle übermannen.",
  "Liebe ist ... wenn einem ohne den anderen die fehlt.",
  "Liebe ist ... wenn einem jemand nicht aus dem Kopf geht.",
  "Liebe ist ... wenn einem beim Küssen die Knie weich werden.",
  "Liebe ist ... wenn eine kleine Geste mehr als alle Worte sagt.",
  "Liebe ist ... wenn ein neues Kleid ihn ganz kirre macht.",
  "Liebe ist ... wenn ein Blick von ihr ganz kirre macht.",
  "Liebe ist ... wenn du beim ersten Blick weißt: Das ist sie! Das ist er.",
  "Liebe ist ... wenn drei Worte dein Leben verändern.",
  "Liebe ist ... wenn dir der Inhalt wichtiger ist als die Verpackung.",
  "Liebe ist ... wenn die Zeit ohne ihn einfach nicht vergehen will.",
  "Liebe ist ... wenn die Versuchung keine Chance hat.",
  "Liebe ist ... wenn die Träume sich immer nur um den einen drehen.",
  "Liebe ist ... wenn die Lippen spreche4n - aber kein Wort zu hören ist.",
  "Liebe ist ... wenn die Jahre immer mehr werden - und das Gefühl kein bisschen weniger.",
  "Liebe ist ... wenn die Jahre ihr nichts anhaben können.",
  "Liebe ist ... wenn die Gefühle unendlich tief gehen.",
  "Liebe ist ... wenn die Gefühle so wild sind wie bei Tarzan Jane.",
  "Liebe ist ... wenn die Gefühle Purzelbäume schlagen.",
  "Liebe ist ... wenn die Gefühle immer wieder neu erblühen.",
  "Liebe ist ... wenn die Gefühle füreinander jeden Tag ein bisschen wachsen.",
  "Liebe ist ... wenn die Gefühle alles sprengen.",
  "Liebe ist ... wenn die Gedanken immer nur um den einen Menschen kreisen.",
  "Liebe ist ... wenn dich deine Gefühle völlig aus der Bahn werfen.",
  "Liebe ist ... wenn der morgendliche Abschiedskuss überhaupt nicht mehr aufhört.",
  "Liebe ist ... wenn der Gedanke an ihn ihr Herz zum Klingen bringt.",
  "Liebe ist ... wenn der Gedanke an ihn den Montag erträglich macht.",
  "Liebe ist ... wenn der Ehemann der beste Flirtpartner bleibt.",
  "Liebe ist ... wenn der Abschied am Montagmorgen besonders schwer fällt.",
  "Liebe ist ... wenn dein Herz singt, singt, singt.",
  "Liebe ist ... wenn dein Herz plötzlich Flügel bekommt.",
  "Liebe ist ... wenn dein Herz dir den weg zeigt.",
  "Liebe ist ... wenn das Leben ohne ihn einfach nicht mehr schmeckt.",
  "Liebe ist ... wenn das Herz zum Herzen spricht.",
  "Liebe ist ... wenn das Herz bei jedem Gedanken an sie einen Hüpfer macht.",
  "Liebe ist ... wenn das Handy die kürzeste Verbindung zwischen zwei Herzen ist.",
  "Liebe ist ... wenn das Glück ganz dicht neben dir sitzt.",
  "Liebe ist ... wenn beide nur noch die drei berühmten Worte im Kopf haben.",
  "Liebe ist ... wenn bei 1 + 1 eine kleine 3 rauskommt.",
  "Liebe ist ... wenn aus einem Teufelchen ein kleiner Engel wird.",
  "Liebe ist ... wenn aus Anbändeln was Festes wird.",
  "Liebe ist ... wenn auch er mal Juniors Windeln wechselt.",
  "Liebe ist ... wenn allein der Gedanke an ihn sie erbeben lässt.",
  "Liebe ist ... wenigstens so zu tun, als ob es schmecken würde.",
  "Liebe ist ... was zwei Menschen zusammenführt - egal wie schwer der Weg ist.",
  "Liebe ist ... was unserem Leben erst die Würze gibt.",
  "Liebe ist ... was nie aufhört.",
  "Liebe ist ... was Liebes am und was Leckeres im Kühlschrank.",
  "Liebe ist ... was Herzliches am - und was Herzhaftes im Kühlschrank.",
  "Liebe ist ... was die ganze Welt zusammenhält.",
  "Liebe ist ... was dich einen schweren Tag in Sekunden vergessen lässt.",
  "Liebe ist ... was dich aus heiterem Himmel trifft.",
  "Liebe ist ... was alle Zeiten überdauert.",
  "Liebe ist ... was alle Hindernisse überwindet.",
  "Liebe ist ... während der WM die Familie nicht ganz zu vergessen.",
  "Liebe ist ... vor lauter Glück den Boden unter den Füßen zu verlieren.",
  "Liebe ist ... vor den Kindern die schlimmen Worte zu verschlucken.",
  "Liebe ist ... vom letzten Urlaub zu träumen.",
  "Liebe ist ... voller Überraschungen.",
  "Liebe ist ... Verantwortung für ein neues Leben zu übernehmen.",
  "Liebe ist ... überraschend Post zu bekommen.",
  "Liebe ist ... überall sein Gesicht zu sehen.",
  "Liebe ist ... sofort zu sehen, wenn sie geputzt hat.",
  "Liebe ist ... so süß wie zwei heiße Tassen Schokolade.",
  "Liebe ist ... sie zur Frau des Jahres zu machen. Jedes Jahr wieder.",
  "Liebe ist ... sie nie aus den Augen zu verlieren.",
  "Liebe ist ... sie nicht aufs Glatteis zu führen.",
  "Liebe ist ... sie mit Karten für ihren Lieblingsfilm zu überraschen.",
  "Liebe ist ... sie jedes Mal aus dem Wasser zu retten, obwohl sie schwimmen kann.",
  "Liebe ist ... sie ins Bett zu tragen.",
  "Liebe ist ... sie in den höchsten Tönen zu loben.",
  "Liebe ist ... sie immer mal wieder mit Kleinigkeiten zu überraschen.",
  "Liebe ist ... sie die neuen Tapeten aussuchen zu lassen.",
  "Liebe ist ... sie das neue Auto fahren lässt.",
  "Liebe ist ... sie beim Schlussverkauf zu begleiten.",
  "Liebe ist ... sie bei einem kleinen Malheur zu trösten.",
  "Liebe ist ... sie bei der Hausarbeit zu unterstützen.",
  "Liebe ist ... sie auf die romantische Art zu erobern.",
  "Liebe ist ... sie auf dem Weg zur Arbeit wie zufällig treffen.",
  "Liebe ist ... sie auch ungeschminkt wunderschön zu finden.",
  "Liebe ist ... sie auch mal gewinnen zu lassen.",
  "Liebe ist ... sich zusammenkuscheln, um Energie zu sparen.",
  "Liebe ist ... sich zu freuen, dass man endlich eine Familie ist.",
  "Liebe ist ... sich von seinem liebsten Stück zu trennen, um ihr einen Ring zu kaufen.",
  "Liebe ist ... sich vertrauensvoll führen zu lassen.",
  "Liebe ist ... sich täglich neu das Glück zu schenken.",
  "Liebe ist ... sich Sorgen zu machen, wenn sie abends lange wegbleibt.",
  "Liebe ist ... sich seine Heldentaten immer und immer wieder anzuhören.",
  "Liebe ist ... sich noch schnell in seine Wärme zu kuscheln, wenn er aufgestanden ist.",
  "Liebe ist ... sich manchmal wieder wie ein Kind zu fühlen.",
  "Liebe ist ... sich kopfüber ins Glück zu stürzen.",
  "Liebe ist ... sich jeden Tag mindestens einmal in den Arm zu nehmen.",
  "Liebe ist ... sich jeden Tag ein Lächeln zu schenken.",
  "Liebe ist ... sich jeden Abend eine neue Geschichte auszudenken.",
  "Liebe ist ... sich in die besten Sachen werfen und mal wieder groß ausgehen.",
  "Liebe ist ... sich in den besten Fummel zu werfen und sie mal wieder groß auszuführen.",
  "Liebe ist ... sich im Haushalt nützlich zu machen.",
  "Liebe ist ... sich glücklich an seinen kleinen Bauch zu schmiegen.",
  "Liebe ist ... sich gemeinsam gegen die Stürme des Lebens zu stellen.",
  "Liebe ist ... sich gemeinsam ein kleines Paradies zu schaffen.",
  "Liebe ist ... sich gegenseitig durchs Leben zu leuchten.",
  "Liebe ist ... sich ganz viel Zeit füreinander zu nehmen.",
  "Liebe ist ... sich ganz viel gemeinsame Zeit zu nehmen.",
  "Liebe ist ... sich ganz oft in den Arm zu nehmen.",
  "Liebe ist ... sich für SIE die Hände schmutzig zu machen.",
  "Liebe ist ... sich für seinen Spaß die Frisur zu ruinieren.",
  "Liebe ist ... sich für ihn schön zu machen.",
  "Liebe ist ... sich für den Partner in Schale zu werfen.",
  "Liebe ist ... sich einen schönen Abend zu gönnen - das neue Gehalt ist ja schon unterwegs.",
  "Liebe ist ... sich eine lange weite Reise mit ihm zu wünschen.",
  "Liebe ist ... sich ein paar Tage Sonne zu schenken.",
  "Liebe ist ... sich blind seiner Führung anzuvertrauen.",
  "Liebe ist ... sich auf den Frühling zu freuen.",
  "Liebe ist ... sich am Wochenende für sie Feinzumachen.",
  "Liebe ist ... sich (fast) nie zu streiten.",
  "Liebe ist ... selig zu sein, das man ihn hat.",
  "Liebe ist ... seinen Kindern die Wunder der Natur zu erklären.",
  "Liebe ist ... seinen Bingo-Gewinn mit ihr zu teilen.",
  "Liebe ist ... seinem Schatz täglich eine E-Mail zu schicken.",
  "Liebe ist ... seine Scherze mit Humor ertragen.",
  "Liebe ist ... seine Pizza zu essen, obwohl sie hart wie Leder ist.",
  "Liebe ist ... seine Gefühle ganz gerecht zu verteilen.",
  "Liebe ist ... seine alten Kinderbilder anzusehen.",
  "Liebe ist ... sein Taschengeld für sie zu opfern.",
  "Liebe ist ... sein Glück für alle Zeiten festzuhalten.",
  "Liebe ist ... sein Fußballtrikot zu waschen.",
  "Liebe ist ... schöner als der teuerste Schmuck.",
  "Liebe ist ... schon mal mit den guten Vorsätzen anzufangen - gemeinsam.",
  "Liebe ist ... schnell wie der Blitz: Ein Blick - und es hat eingeschlagen.",
  "Liebe ist ... Rot im Kalender zu markieren, wann sie ihn wieder sieht.",
  "Liebe ist ... Rollentausch am Wochenende: Sie das Sofa - er die Kinder.",
  "Liebe ist ... pünktlich zum Essen zu kommen.",
  "Liebe ist ... nur noch Herzchen zu sehen, wenn er wieder da ist.",
  "Liebe ist ... nur den kussfesten Lippenstift zu benutzen.",
  "Liebe ist ... niemals Witze auf seine Kosten zu machen.",
  "Liebe ist ... nie ohne Gute - Nacht - Kuss einzuschlafen.",
  "Liebe ist ... nichts vor ihr verstecken zu müssen.",
  "Liebe ist ... nicht ständig an ihm herumzunörgeln.",
  "Liebe ist ... nicht rumzuzappen, wenn sie ihre Lindenstraße sehen will.",
  "Liebe ist ... nicht in seinem Telefonbuch zu schnüffeln.",
  "Liebe ist ... nicht die Verpackung, sondern der Inhalt.",
  "Liebe ist ... neben ihr im Auto zu sitzen, ohne ein Wort zu sagen.",
  "Liebe ist ... nachzudenken, ob er nicht vielleicht doch recht hat.",
  "Liebe ist ... nachts am Krankenbett zu wachen.",
  "Liebe ist ... nach einem Streit den ersten Schritt zu tun.",
  "Liebe ist ... morgens im Bad schon Party zu machen.",
  "Liebe ist ... mit seinem Sohn Ball zu spielen.",
  "Liebe ist ... mit kleinen Gesten große Gefühle zu zeigen.",
  "Liebe ist ... mit Ihr gemeinsam die Zukunft zu planen.",
  "Liebe ist ... mit ihr einen Einkaufsbummel zu machen.",
  "Liebe ist ... mit ihm zu leiden, wenn er Heuschnupfen hat.",
  "Liebe ist ... mit der Familie Picknick zu machen.",
  "Liebe ist ... mit den Kindern in ihr Lieblingsrestaurant zu gehen.",
  "Liebe ist ... mit dem Kind im Garten Dinos fangen.",
  "Liebe ist ... mit Blicken reden und sich stumm verstehen.",
  "Liebe ist ... mit allen Mitteln um sein Glück zu kämpfen.",
  "Liebe ist ... mehr als gute Freundschaft.",
  "Liebe ist ... manchmal wie das Wetter - sehr wechselhaft.",
  "Liebe ist ... manchmal Herzzerreißend.",
  "Liebe ist ... manchmal ganz schön Schmerzhaft.",
  "Liebe ist ... manchmal eine Last. Aber eine süße.",
  "Liebe ist ... manchmal ein Schauspiel.",
  "Liebe ist ... manchmal auch schmerzhaft.",
  "Liebe ist ... manchmal auch ein Geduldsspiel.",
  "Liebe ist ... mal wieder so zu tun, als wär´s das erste Mal.",
  "Liebe ist ... lebenslang Partner zu sein.",
  "Liebe ist ... küssen, bis die Lippen brennen.",
  "Liebe ist ... kleine Risse ganz schnell zu kitten.",
  "Liebe ist ... jeden seiner Briefe auswendig zu kennen.",
  "Liebe ist ... ist jemand, der trotz allem zu dir hält.",
  "Liebe ist ... in seinen Armen am schönsten.",
  "Liebe ist ... in schwerer See im selben Boot zu sitzen.",
  "Liebe ist ... in Ihren Armen wunderbar.",
  "Liebe ist ... in Gedanken immer beieinander zu sein.",
  "Liebe ist ... in einem einzigen Brief gar nicht auszudrücken.",
  "Liebe ist ... in den Augen des anderen immer jung und schön zu bleiben.",
  "Liebe ist ... immer wieder eine lockende Melodie.",
  "Liebe ist ... immer ein guter Zuhörer zu sein.",
  "Liebe ist ... im Licht der Kerze noch viel schöner.",
  "Liebe ist ... im Büro den ganzen Tag an ihn zu denken.",
  "Liebe ist ... ihren Duft in der Nase zu haben, obwohl sie gar nicht da ist.",
  "Liebe ist ... ihre Wäsche hereinzuholen, wenn es regnet.",
  "Liebe ist ... ihre Lieblingspflanzen mitzubringen.",
  "Liebe ist ... ihr zu sagen wie sehr er sie vermisst.",
  "Liebe ist ... ihr zu helfen, auch wenn gerade die Kumpels warten.",
  "Liebe ist ... ihr wenigstens einen Abend in der Woche freizugeben.",
  "Liebe ist ... ihr täglich ein Kompliment zu machen - auch wenn´s mal nicht auf die feine Art ist.",
  "Liebe ist ... ihr sonnabends den schweren Einkaufswagen zu schieben.",
  "Liebe ist ... ihr so oft wie möglich zu schreiben.",
  "Liebe ist ... ihr per Computer zu zeigen, wie sehr man sie mag.",
  "Liebe ist ... ihr Oberpfleger zu sein, wenn´s ihr mal nicht gut geht.",
  "Liebe ist ... ihr noch ein 1/2 Stündchen Schlaf zu gönnen.",
  "Liebe ist ... ihr morgens zu sagen , wie blendend sie aussieht.",
  "Liebe ist ... ihr morgens die Windschutzscheibe Freizukratzen.",
  "Liebe ist ... ihr mit einem Fax den Tag zu verschönern.",
  "Liebe ist ... ihr ins Ohr zu flüstern: Du bist meine Königin.",
  "Liebe ist ... ihr einen bildschönen Garten zu pflanzen.",
  "Liebe ist ... ihr ein Wochenende voller Romantik zu schenken.",
  "Liebe ist ... ihr die schlechte Laune wegzuküssen.",
  "Liebe ist ... ihr die Frühlingsdiät mit einer Belohnung zu versüßen.",
  "Liebe ist ... ihr die Finanzen zu überlassen. Frauen können das eh besser.",
  "Liebe ist ... Ihr die Autoheizung mollig warm einzustellen.",
  "Liebe ist ... ihr das Haus seiner Kindheit zu zeigen.",
  "Liebe ist ... ihr das auf jede verrückte Art zu zeigen.",
  "Liebe ist ... ihr Bild immer auf dem Schreibtisch zu haben.",
  "Liebe ist ... ihr beim Hausputz zu helfen.",
  "Liebe ist ... ihr bei der Wäsche zu helfen.",
  "Liebe ist ... ihr am Wochenende Blumen mitzubringen.",
  "Liebe ist ... ihr alle Bürden abzunehmen.",
  "Liebe ist ... ihn zu loben, wenn er mal den Handwerker spielt.",
  "Liebe ist ... ihn unverhofft ganz fest zu drücken.",
  "Liebe ist ... ihn schlechte Nachrichten ganz schnell vergessen zu lassen.",
  "Liebe ist ... ihn sanft daran zu erinnern das die Feiertage vorbei sind.",
  "Liebe ist ... ihn nicht mit Lockenwicklern und Maske zu erschrecken.",
  "Liebe ist ... ihn nicht im Fernseh-Sessel versauern zu lassen.",
  "Liebe ist ... ihn mit einer Geburtstagstorte zu überraschen.",
  "Liebe ist ... ihn in Gedanken zu umarmen.",
  "Liebe ist ... ihn in die richtigen Geschäfte zu führen.",
  "Liebe ist ... ihn in dem Glauben zu lassen, dass er der Chef ist.",
  "Liebe ist ... ihn in das Nachtgebet mit einzuschließen.",
  "Liebe ist ... IHN das neue Auto aussuchen zu lassen.",
  "Liebe ist ... ihn beim Rasieren ruhig singen zu lassen.",
  "Liebe ist ... ihn bei zuviel Arbeit öfter mal auf andere Gedanken zu bringen.",
  "Liebe ist ... ihn abzuholen, wenn er Überstunden machen muss.",
  "Liebe ist ... ihm zu zeigen, dass er ihr Supermann ist.",
  "Liebe ist ... ihm vor der Frühschicht die Stullen zu machen.",
  "Liebe ist ... ihm seine Lieblingshose immer wieder zu flicken.",
  "Liebe ist ... ihm sein Leibgericht zu kochen. Auch wenn sie es selbst nicht mag.",
  "Liebe ist ... ihm Küsse zu faxen.",
  "Liebe ist ... ihm Komplimente für seine Badehosenfigur zu machen.",
  "Liebe ist ... ihm jeden Wunsch von den Augen abzulesen.",
  "Liebe ist ... ihm immer das größte Stück Torte zu geben.",
  "Liebe ist ... ihm ganz unauffällig zu zeigen, wie´s um ihr Herz steht.",
  "Liebe ist ... ihm fürs Eisvergnügen einen neuen Hockeyschläger zu schenken.",
  "Liebe ist ... ihm für seinen Fußball-Abend die Naschration mitzubringen.",
  "Liebe ist ... ihm ein Trimm dich -Programm zu verpassen.",
  "Liebe ist ... ihm auch zwischendurch ein Geschenk zu machen.",
  "Liebe ist ... himmlisch.",
  "Liebe ist ... heute die Valentinstag-Karte zu besorgen.",
  "Liebe ist ... heute Abend zusammen unterm Vollmond träumen.",
  "Liebe ist ... heute Abend gemeinsam die Mondfinsternis zu bestaunen.",
  "Liebe ist ... Herzflimmern. Schon bei dem Gedanken an ihn.",
  "Liebe ist ... heißer als das Kaminfeuer.",
  "Liebe ist ... heiße E-Mails übers Netz zu senden.",
  "Liebe ist ... grenzenlos.",
  "Liebe ist ... gerade in schlechten Zeiten die Sonne im Herzen zu haben.",
  "Liebe ist ... genau zu wissen, wann das Glück an der Tür klopft.",
  "Liebe ist ... gemeinsam Zukunftspläne zu schmieden.",
  "Liebe ist ... gemeinsam was für die Fitness zu tun.",
  "Liebe ist ... gemeinsam Luftschlösser zu bauen.",
  "Liebe ist ... gemeinsam im Himmelbett aufzuwachen.",
  "Liebe ist ... gemeinsam eine neue Küche zu planen.",
  "Liebe ist ... gemeinsam die Sterne vom Himmel zu holen.",
  "Liebe ist ... gemeinsam die Seele baumeln zu lassen.",
  "Liebe ist ... gemeinsam die Klippen des Lebens zu umschiffen.",
  "Liebe ist ... gemeinsam den Winterurlaub zu planen.",
  "Liebe ist ... gemeinsam auf Wolke 7 durchs Leben zu schweben.",
  "Liebe ist ... gemeinsam auf einer Wolke zu schweben.",
  "Liebe ist ... gemeinsam auf der Welle des Glücks zu reiten.",
  "Liebe ist ... gemeinsam auf dem Strom des Lebens zu segeln.",
  "Liebe ist ... gemeinsam alt zu werden.",
  "Liebe ist ... gemeinsam alle Hindernisse zu überwinden.",
  "Liebe ist ... gemeinsam abheben - Richtung Paradies.",
  "Liebe ist ... für sie das Sofa mit den Joggingschuhen zu tauschen.",
  "Liebe ist ... für jeden da - wirklich für JEDEN.",
  "Liebe ist ... für ihn etwas ganz Ausgefallenes zu kochen.",
  "Liebe ist ... für ihn einen zärtlichen Kosenamen zu erfinden.",
  "Liebe ist ... fast so schön, wie ein Schokoladenkeks.",
  "Liebe ist ... fast alles über sich ergehen zu lassen.",
  "Liebe ist ... etwas, wovon er gar nicht genug bekommen kann.",
  "Liebe ist ... etwas, was man jeden Tag pflegen muss.",
  "Liebe ist ... es mit dem Rasierwasser nicht zu übertreiben.",
  "Liebe ist ... es lieber gleich rauslassen, als es mit sich rumzuschleppen.",
  "Liebe ist ... es ihr auf 100 verschiedene Arten zu sagen.",
  "Liebe ist ... es ihr auch per Computer zu sagen.",
  "Liebe ist ... es allen zu zeigen, wem man sein Herz geschenkt hat.",
  "Liebe ist ... erfrischend - wie ein Eis im Frühling.",
  "Liebe ist ... eng umschlungen einzuschlafen.",
  "Liebe ist ... endlich mal wieder ein Abend zu zweit.",
  "Liebe ist ... einen wunderschönen Moment im Herzen festzuhalten.",
  "Liebe ist ... einen letzten Blick auf sein Aussehen zu werfen.",
  "Liebe ist ... eine zarte Pflanze. Sie muss täglich gehegt werden.",
  "Liebe ist ... eine Vollmondnacht, eine Parkbank - und wir beide.",
  "Liebe ist ... eine süße Zwangsjacke.",
  "Liebe ist ... eine selbst erlebte Liebesgeschichte.",
  "Liebe ist ... EINE Seele in ZWEI Körpern.",
  "Liebe ist ... eine rote Rose auf dem Frühstückstablett.",
  "Liebe ist ... eine Party zu zweit.",
  "Liebe ist ... eine große Portion selbstgemachter Früchtebrei.",
  "Liebe ist ... eine Krankheit die sich meist durch Hautkontakt überträgt.",
  "Liebe ist ... ein Wochenende zu zweit allein. Die Welt muss draußen bleiben.",
  "Liebe ist ... ein wahrer Schatz.",
  "Liebe ist ... ein Tänzchen um den Küchentisch.",
  "Liebe ist ... ein Stück Himmel auf Erden.",
  "Liebe ist ... ein ständiges auf und ab.",
  "Liebe ist ... ein Signal.",
  "Liebe ist ... ein Seufzer aus tiefstem Herzen.",
  "Liebe ist ... ein prickelndes Schaumbad zu nehmen und sich ganz doll auf ihn zu freuen.",
  "Liebe ist ... ein Paar, ein Boot, ein Sonnenuntergang - und kein Ziel.",
  "Liebe ist ... ein Labyrinth - bis man die/den Richtige/n gefunden hat.",
  "Liebe ist ... ein Kuss per Post.",
  "Liebe ist ... ein köstliches Abendessen ohne die Kinder.",
  "Liebe ist ... ein heißer Kuss von kühlen Lippen.",
  "Liebe ist ... ein Geschenk des Himmels.",
  "Liebe ist ... ein gemütliches Wochenende mit der Familie.",
  "Liebe ist ... ein festes Fundament.",
  "Liebe ist ... ein bunter Regen für seinen Sonnenschein.",
  "Liebe ist ... ein besonders zarter Gute - Nacht - Kuss, weil sie schon schläft.",
  "Liebe ist ... ein Bad zu zweit - bis die Wanne überläuft.",
  "Liebe ist ... ein Anruf bei jeder Gelegenheit.",
  "Liebe ist ... ein Anruf aus dem Büro.",
  "Liebe ist ... ein Abend mit Rosen und Champagner.",
  "Liebe ist ... ein 5-Sterne-Programm auf der Couch.",
  "Liebe ist ... doppelte Freude.",
  "Liebe ist ... Dinner for one.",
  "Liebe ist ... dieses uralte, ewig neue Spiel von verführen und sich verführen lassen.",
  "Liebe ist ... dieses uralte Spiel von Verführen und Verführung.",
  "Liebe ist ... dieses unerträglich schöne Schwebegefühl.",
  "Liebe ist ... dieses unbeschreibliche Gefühl: Es ist, als ob du schwebst.",
  "Liebe ist ... dieses Gefühl, dem Himmel näher zu sein als der Erde.",
  "Liebe ist ... diese unerklärliche Anziehungskraft.",
  "Liebe ist ... diese süße Last.",
  "Liebe ist ... die Zukunft sicher durch die Gegenwart zu bringen.",
  "Liebe ist ... die Wohnung herzlich einzurichten.",
  "Liebe ist ... die Woche mit einem Kuss beginnen zu lassen.",
  "Liebe ist ... die Welt mit dem Herzen zu sehen.",
  "Liebe ist ... die Welt durch die Augen eines Kindes zu sehen.",
  "Liebe ist ... die Wärme, die von innen kommt.",
  "Liebe ist ... die Tage zu zählen, bis er wieder da ist.",
  "Liebe ist ... die Stunden zu zählen, bis er wieder kommt.",
  "Liebe ist ... die stärkste Antriebskraft.",
  "Liebe ist ... die Sonne im Herzen zu tragen.",
  "Liebe ist ... die schönste Frage der Welt zu genießen.",
  "Liebe ist ... die schönste Ablenkung vom täglichen Trott.",
  "Liebe ist ... die schönen Augenblicke mit der Kamera festzuhalten.",
  "Liebe ist ... die nervenden Gewohnheiten des anderen zu verstehen.",
  "Liebe ist ... die Meinung des Partners zu akzeptieren.",
  "Liebe ist ... die köstliche Eiscreme ehrlich zu teilen.",
  "Liebe ist ... die Kinder jeden Tag zu loben.",
  "Liebe ist ... die Gewissheit, dass das Glück nur eine Armlänge entfernt ist.",
  "Liebe ist ... die Familien-Räder frühlingsfit zu machen.",
  "Liebe ist ... die Ernte aller Herzenswünsche.",
  "Liebe ist ... die Bremsen zu überprüfen, bevor er losfährt.",
  "Liebe ist ... die beste Zutat für ein glückliches Leben.",
  "Liebe ist ... die beste Pflege. Weil sie doch weiß, wie er leidet.",
  "Liebe ist ... die beste Medizin.",
  "Liebe ist ... die beste Kurve ins Glück.",
  "Liebe ist ... die Arbeit zu teilen.",
  "Liebe ist ... die alten Fotoalben anzusehen.",
  "Liebe ist ... der Zukunft einen Platz zu schaffen.",
  "Liebe ist ... der Weg und das Ziel.",
  "Liebe ist ... der Start in eine schönere Welt.",
  "Liebe ist ... der Sonnenschein des Alters.",
  "Liebe ist ... der Schlüssel zu allem.",
  "Liebe ist ... der Kleber für ein gebrochenes Herz.",
  "Liebe ist ... der Himmel auf Erden.",
  "Liebe ist ... der Hauptgewinn des Lebens.",
  "Liebe ist ... der Halt, den einer dem anderen gibt.",
  "Liebe ist ... der Glanz in den Augen beim ersten Rendezvous.",
  "Liebe ist ... der freie Fall ins Glück.",
  "Liebe ist ... der eigenen Frau nachzupfeifen.",
  "Liebe ist ... der beste Vater von allen zu sein.",
  "Liebe ist ... der beste (und schönste) Problemlöser.",
  "Liebe ist ... den Weg des Lebens gemeinsam gehen.",
  "Liebe ist ... den Tag mit einem Tänzchen zu beginnen.",
  "Liebe ist ... den neuen Lippenstift an ihm zu testen.",
  "Liebe ist ... den Kindern die schönsten Adventsgeschichten vorzulesen.",
  "Liebe ist ... den ganzen Weg des Lebens gemeinsam zu gehen.",
  "Liebe ist ... den anderen zu nehmen wie er ist. Und nicht, wie man ihn haben möchte.",
  "Liebe ist ... den Abwasch einfach mal stehen zulassen.",
  "Liebe ist ... das, was einen schönen Abend verzaubern kann.",
  "Liebe ist ... das wunderschönste Gefühl auf der Welt.",
  "Liebe ist ... das was einen Abend verzaubern kann.",
  "Liebe ist ... das Tapezieren gemeinsam zu lernen.",
  "Liebe ist ... das Spiel der Herzen, bei dem es nur Gewinner gibt.",
  "Liebe ist ... das schönste, was zwei Menschen passieren kann.",
  "Liebe ist ... das schönste Wort der Welt.",
  "Liebe ist ... das schönste Geburtstagsgeschenk.",
  "Liebe ist ... das kostbarste Geschenk.",
  "Liebe ist ... das größte Glück dieser Welt.",
  "Liebe ist ... das größte Geheimnis des Lebens.",
  "Liebe ist ... das gemeinsame Leben wie einen bunten Blumenstrauß zu gestalten.",
  "Liebe ist ... das ewige Spiel von verführen und verführt werden.",
  "Liebe ist ... das Eis von ihrem Auto abzuschaben.",
  "Liebe ist ... das einzige Spiel bei dem es zwei Sieger gibt.",
  "Liebe ist ... das beste Mittel, um Tränen trocknen zu lassen.",
  "Liebe ist ... da zu sein, wenn´s ihr mal schlecht geht.",
  "Liebe ist ... beim Kuscheln das Handy auszuschalten.",
  "Liebe ist ... bei Sonnenuntergang auf der Parkbank zu kuscheln.",
  "Liebe ist ... auf seine Gesundheit zu achten.",
  "Liebe ist ... auch zum zehnten Mal zusammen in ihren Lieblingsfilm zu gehen.",
  "Liebe ist ... auch nach vielen Jahren noch romantisch zu sein.",
  "Liebe ist ... auch in heiklen Situationen Fingerspitzengefühl zu zeigen.",
  "Liebe ist ... Arbeitsteilung: Sie wärmt das Bett an, und er räumt auf.",
  "Liebe ist ... Arbeitsteilung: Sie fürs Feine, er fürs Grobe.",
  "Liebe ist ... an ihn zu denken, wenn er es gar nicht erwartet.",
  "Liebe ist ... an einem kalten Tag in seinen Armen Wärme zu finden.",
  "Liebe ist ... an diesen grauen Tagen wenigstens im Herzen Sommergefühle zu haben.",
  "Liebe ist ... am Wochenende gemeinsam Kekse zu backen.",
  "Liebe ist ... am Wochenende gemeinsam das Vogelhäuschen aufzustellen.",
  "Liebe ist ... am Wochenende für sie zu kochen.",
  "Liebe ist ... am Vatertag abends nicht zu sehr mit ihm zu schimpfen.",
  "Liebe ist ... am langen Sonnabend ganz geduldig mit ihr einkaufen zu gehen.",
  "Liebe ist ... alles zu teilen.",
  "Liebe ist ... alles gemeinsam zu probieren.",
  "Liebe ist ... alle ihre Strafzettel zu bezahlen.",
  "Liebe ist ... alle ihre Sommersprossen zu lieben.",
  "Liebe ist ... ab und zu mal die Rollen zu tauschen.",
  "Liebe ist ... ab auf die Insel. Und dann Hand in Hand übern Strand.",
  "Liebe ist ... ab 30 wieder mit einer Kerze auf der Geburtstagstorte zu beginnen.",
  "Liebe ist ... noch zum fünften Male die Möbel umzustellen.",
  "Liebe ist ... ihr Fahrrad zu reparieren.",
  "Liebe ist ... wenn der Gute - Nacht - Kuss bis zum Morgen dauert.",
  "Liebe ist ... zu wissen, daß er ein Nein nicht ernst nehmen wird.",
  "Liebe ist ... gelassen zuhören, wenn er mal wieder große Sprüche klopft.",
  "Liebe ist ... die schönsten Träume zu teilen.",
  "Liebe ist ... das Feuerwerk des Lebens.",
  "Liebe ist ... bei minus 3 Grad heiße Träume zu haben.",
  "Liebe ist ... wenn der Knoten im Taschentuch sagt: Ich liebe dich.",
  "Liebe ist ... wenn seine Zuneigung hochkarätig ist.",
  "Liebe ist ... wenn man beim Abschied kein Wort heraus bekommt.",
  "Liebe ist ... zwei Herzen - ein Wunsch.",
  "Liebe ist ... zusammen heißen Kaffee am Kamin zu trinken.",
  "Liebe ist ... wie Champagner - er steigt zu Kopf.",
  "Liebe ist ... wenn man zu zweit nur einen Sessel braucht.",
  "Liebe ist ... wenn man weiß: Jetzt darf ich ihn nicht stören.",
  "Liebe ist ... wenn man gern auf sie wartet.",
  "Liebe ist ... sie zu trösten, wenn sie die erste Falte entdeckt hat.",
  "Liebe ist ... sie auch mal mit ins Museum zu nehmen.",
  "Liebe ist ... sie am Sonntag ausschlafen zu lassen.",
  "Liebe ist ... sich nie zu langweilen.",
  "Liebe ist ... sich nie miteinander zu langweilen.",
  "Liebe ist ... sich im Dunkeln anzuziehen, damit sie weiter schlafen kann.",
  "Liebe ist ... seine Hemden zu bügeln, bevor er sie braucht.",
  "Liebe ist ... nie den Hochzeitstag zu vergessen.",
  "Liebe ist ... nicht mehr Geld auszugeben, als er verdient.",
  "Liebe ist ... nicht gleich das Fenster aufreißt, wenn er sich seine Pfeife anzündet.",
  "Liebe ist ... nicht gleich böse werden, wenn er mal schlechte Laune hat.",
  "Liebe ist ... na, Sie wissen schon: Ole´.",
  "Liebe ist ... im richtigen Augenblick das Gleiche zu denken.",
  "Liebe ist ... im Büro noch schnell einen Brief an ihn zu tippen.",
  "Liebe ist ... ihr zärtlich den Rü;cken trocken rubbeln.",
  "Liebe ist ... ihr einen Kuss zu geben, auch wenn Grippezeit ist.",
  "Liebe ist ... ihr die müden Füße zu massieren, wenn sie vom Einkaufen kommt.",
  "Liebe ist ... ihn auch mit Bartstoppeln zu küssen.",
  "Liebe ist ... ihm nie zu zeigen, was eine Harke ist.",
  "Liebe ist ... gar nicht hinzugucken, wenn er auf die Krawatte gekleckert hat.",
  "Liebe ist ... die Winterfreuden gemeinsam zu genießen.",
  "Liebe ist ... die schönste Seite im Buch des Lebens.",
  "Liebe ist ... auf einer Bank ganz eng zusammenzurücken.",
  "Liebe ist ... auch in schlechten Zeiten zusammenhalten.",
  "Liebe ist ... auch an einem verregnetem Urlaubstag singen zu können.",
  "Liebe ist ... alle Verabredungen abzusagen, wenn er frei hat.",
  "Liebe ist ... laufend etwas Neues.",
  "Liebe ist ... Der große Preis.",
  "Liebe ist ... sie in den Arm zu nehmen, wenn sie es braucht.",
  "Liebe ist ... ihr ganz sanft die Haare aus der Stirn zu streichen.",
  "Liebe ist ... die Fenster zusammen zu putzen.",
  "Liebe ist ... wenn er beim Parfü;mkauf von ihr träumt.",
  "Liebe ist ... zu wissen, der Beruf geht vor.",
  "Liebe ist ... wenn man genau weiß, warum ihre Augen leuchten.",
  "Liebe ist ... der Hauptgewinn des Lebens."
]

exports.handler = (event, context, callback) => {
  const alexa = Alexa.handler(event, context)
  alexa.APP_ID = APP_ID
  // To enable string internationalization (i18n) features, set a resources object.
  alexa.resources = languageStrings
  alexa.registerHandlers(handlers)
  alexa.execute()
}

const handlers = {
  'LaunchRequest': function () {
    this.emit('GetLoveIs')
  },
  'GetLoveIs': function () {
    const index = Math.floor(Math.random() * loveIs.length);
    const text = loveIs[index]
    this.emit(':tellWithCard', text, this.t('SKILL_NAME'), text)
  },
  'AMAZON.HelpIntent': function () {
    this.emit(':tell', this.t('HELP_MESSAGE'))
  },
  'AMAZON.CancelIntent': function () {
    this.emit(':tell', this.t('STOP_MESSAGE'))
  },
  'AMAZON.StopIntent': function () {
    this.emit(':tell', this.t('STOP_MESSAGE'))
  }
}
